### ISSUE TITLE
Age not captured for non ELCO women

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#100]
DOB is not asked for non ELCO women, which results in 'NaN' in the screenshot below.  Age should be asked for all women, not only ELCO women.  @numeranazneen assigning to you.  Pls update the forms
(NewHH and Census) to ensure age is asked for all women.

![screen shot 2015-10-07 at 4 35 33 pm](https://cloud.githubusercontent.com/assets/3488986/10350382/b77b1f98-6d11-11e5-8a8d-4f12f90ab48f.png)

**Comment by numeranazneen** [comment]
Yeah, KZ and her team has removed this question for Non-ELCO because DoB collection is a hassle for the enumerators. I guess they'd either want this to be blank instead of 'NaN' or they'd agree to collect DoB for all. I dropped a mail to JHU team . Let's see what their decision is.

**Comment by cagulas** [comment]
If DOB is not collected, then we'd have to auto-assign a DOB for these women.  Better to ask for the real DOB.  I saw your mail to them, thx.  Would be good to get Kelsey on GitHub to review these issues as well.

**Comment by numeranazneen** [comment]
I agree, instead of having a fake DoB, it's better to collect this. I think KZ and team will agree and add this.

**Comment by cagulas** [comment]
KZ confirmed we can move up DOB to be asked of all women.  @numeranazneen did you already update this?  If so, please close this issue.
