### ISSUE TITLE
Replace MWRA with ELCO in app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#104]
In HH register view, please replace MWRA with ELCO in the filter view as well as the column heading that says No. of MWRA (should be No. of ELCO) instead.  Make sure to add a period (.) after No. in No. of ELCO.

![screen shot 2015-10-07 at 2 12 07 pm](https://cloud.githubusercontent.com/assets/3488986/10347130/8781c8ac-6d00-11e5-8b19-09b141c89b39.png)

@klzeller @numeranazneen

**Comment by raihan-mpower** [comment]
this is done and hence closing the issue
