### ISSUE TITLE
Update in FWNewHH and Census Form

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#105]
Please download the updated XLS forms from ona.io and integrate with the app-
1. Add ELCO count calculation; strike-through MWRA calculation
2. Added two hidden variables for developers use- user_type and external_user_ID

@cagulas @sohelsarder @ndisha

**Comment by cagulas** [comment]
@numeranazneen the MWRA variables can be deleted.  I struck-through them initially, so others could see what was to be removed from the form.  Please delete these if you haven't already.

**Comment by numeranazneen** [comment]
I already did. :)

**Comment by cagulas** [comment]
Awesome :+1:
