### ISSUE TITLE
What is plan to hide unused registers at launch?

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#107]
According to my understanding, at launch, FWA workers will use Household and ELCO registers only.  After 90 days, ANC, PNC, and Child registers will be used.

Is there a plan to hide these 3 registers for the launch, or deactivate them to prevent FWA from opening them?

What about the Reporting and Video modules?  These still show content from India deployment.

@numeranazneen @raihan-mpower @klzeller

**Comment by numeranazneen** [comment]
The additional registers, reporting and videos had been locked before launch.
