### ISSUE TITLE
Mauzapara not shown in latest BD release

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#109]
See screenshot below. This is in the Oct 21 release.  The mauza-para should appear above HH head name, but it's blank:

![screen shot 2015-10-25 at 4 12 40 pm](https://cloud.githubusercontent.com/assets/3488986/10714640/5caec1b6-7b33-11e5-9522-b191f2ee311b.png)

This was done using cgtest login credentials.

**Comment by raihan-mpower** [comment]
this has been fixed in latest release
