### ISSUE TITLE
App UI/UX guidelines

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client#113]
- Registers
- Reporting
- Media
- Home screen
- Multiple screensizes (proportional guidelines)
- Walton, Samsung Tab 3 7.0, Samsung 10", Sony Xperia Z3 8", etc.

**Comment by cagulas** [comment]
@rowo can we close this issue?

**Comment by rowo** [comment]
Yep. Added https://github.com/OpenSRP/opensrp-client/issues/148.
