### ISSUE TITLE
Update in FWNewHH and Census

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#115]
Added a hidden field 'form_name' in both FWNewHH and Census Form. This field is required for csv export purpose. The updated forms are in ona.io.

@cagulas @sohelsarder @asifur77

**Comment by cagulas** [comment]
@numeranazneen I think this needs to be a calculate field.  hidden fields mean the value is being pulled into the form from somewhere else.  It would probably be easier to add calculate field and just assign the value of the form id to the field.  Is there a specific reason why it needs to be hidden field?

**Comment by numeranazneen** [comment]
mmmm..no, no specific reason, the dev just needed this value in the form, and I had to make it hidden, as there were some other Hidden fields like 'user_type', external_user_id' which are actually hidden in the form (but not pulling data from somewhere else), so I thought it'll work in that way.

**Comment by cagulas** [comment]
Oh I see.  Maybe I misunderstood user_type and external_user_id fields.  These are fixed values?  If so, then they should be calculate fields as well.  I had thought these were being pulled into the form from somewhere.

**Comment by numeranazneen** [comment]
Ok. Then what should I put in the calculation fields for these two variables? For ' user_type' I can put 'FWA' but for 'external_user_id', I am not sure what should I put? Because Dev Team will allocate JiVitA user's ID in this field.

**Comment by cagulas** [comment]
Yes, if FWA is fixed value, then put as calculate field.  I am confused by external_user_id field, though.  FWA is not JiVita worker, so why does Jivita user id need to be pulled into FWA form?

**Comment by raihan-mpower** [comment]
this is done and hence closing the issue
