### ISSUE TITLE
Location management & Role managemnt during user authentication - done in OpenMRS and passed on to OpenSRP

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#12]
How will the client will handle this? Can we handle this outside the form & have it done before each registration form is launched - have them pick the location (i.e., village).

Related to: https://github.com/OpenSRP/opensrp-server/issues/9

@raihan-mpower @maimoonak @sohelsarder @julkarnain @wahid-nwr @raufdesu @dimasciput

**Comment by mberg** [comment]
@mndisha can you please elaborate a bit more what you mean about location
management?

thanks!

**Comment by ndisha** [comment]
OK, we will have user authentication handled on OpenMRS, with the following features being handled:
-Allow for entry of username & password
-Send these to OpenMRS for authentication
-Receive the user details, including the role & location of the user - here we are talking about the ANM location which will then be passed to her clients on form launch, instead of selection of the client location for each submission.
-Check on the access rights before allowing the user to see each form

**Comment by ndisha** [comment]
@dimasciput @raihan-mpower is the location tree functional? We are working on the HH register and we need confirmation that the locations can now be loaded from OpenMRS.

**Comment by ndisha** [comment]
@cagulas we need to get the different countries requirements on the frontline healthcare workers roles; can we start that conversation? The location management bit of this requirement is done (or nearly done) as per todays call.

**Comment by cagulas** [comment]
Sure, this will be for V2?  V1 will involve one health worker only from each site, so only one user role is needed at the moment I believe.  Let's have a quick call to discuss the best way to document permissions and user roles for V2.  For example, this issue is about OpenMRS permissions as well as form and data viewing permissions on the client side, or just the latter?

**Comment by ndisha** [comment]
@cagulas am closing this issue - since Role-based management is not a priority and will be considered in V2, potentially.
