### ISSUE TITLE
The date format used in the app should match dd/mm/yyyy 

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#124]

**Comment by cagulas** [comment]
@numeranazneen so far, @koros and I have not been able to replicate this.  For both of us (both using Samsung tabs), the date format is correct, i.e dd/mm/yyyy.

This points to a device-specific issue.  What device or devices are you seeing this problem on?  Can you try on a different type of device and see if the issue remains?  Is the device set to Bengali language and input?  

Can you also try adjusting some of the date format settings and try different combinations to see if the issue gets resolved?  For example, set the device language and input to English and try different date formats, then do the same for Bengali?

**Comment by numeranazneen** [comment]
We checked that in two tablets- Walpad 8G  and Symphony Xplorer T7 pro. In both the tablets we found the same problem. We changed the date settings to dd-mm-yyyy format but still showing mm-dd-yyyy in the app forms. 

Is there any possibility that it can an OS related issue? because in both the tablets the OS was Kitkat. Have you checked that in Kitkat or Lolypop?

**Comment by koros** [comment]
Hi @numeranazneen this issues appears tricky i had mentioned it to @raihan-mpower, at the moment the other possible cause could be way the web view on the device is displaying/reading based on the set locale, try changing your locale to english-us see what happens.

**Comment by cagulas** [comment]
@numeranazneen is this resolved yet?  If not, which locale are you using on the devices?

**Comment by numeranazneen** [comment]
Not resolved yet. We have changed the locale to English, but still didn't see any change in the Date Format. 

Considering the importance of other issues, I think we can skip fixing this issue. Raihan was saying it may impact other features if we forcefully try to update the format. So, it's Ok the way we have the date currently.

**Comment by raihan-mpower** [comment]
this has been fixed with applied formating in form logic in xls
