### ISSUE TITLE
Enketo form does not load on latest BD apk on genymotion

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#126]
See below.  This is App version number 14.0, build date Jan 10, 2016.  This is on my genymotion machine.  I wasn't able to test on a real tablet, because I cannot access the app settings to change base url and port on my Samsung tab, so I always use Genymotion instead.  This is the first time the form won't open for me.

![gif](https://cloud.githubusercontent.com/assets/3488986/12240031/899be4f2-b859-11e5-81c3-915f94c6cb9c.gif)

**Comment by raihan-mpower** [comment]
can you delete, clear data in your end? it is working in my genymotion

**Comment by cagulas** [comment]
Clear data did not work, but I uninstalled the app and reinstalled it from play store, and it worked now.

Is this app using the faster Enketo forms yet?  I thought it was implemented already, but I don't see the switch language option in the form.
