### ISSUE TITLE
Calendar issue- If DATE field is tapped outside the calendar while setting date, the field is locked and never shows the calendar again

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#127]
@cagulas @raihan-mpower

**Comment by numeranazneen** [comment]
Sorry...I think @cagulas already this in github. So, I am closing it.

**Comment by koros** [comment]
@numeranazneen issue fixed in the latest code please verify on your end

**Comment by numeranazneen** [comment]
Checked. It's fixed. Thanks.
