### ISSUE TITLE
Save the last incomplete data for all forms

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#129]
As of now it’s working only for HH registration form which launches from ‘+’ button

@cagulas @raihan-mpower

**Comment by koros** [comment]
Hi @numeranazneen all forms on the faster forms branch should have this logic in place however if you do notice any that is missing or inconsistent please create an issue, test on you end then let me know.

**Comment by koros** [comment]
Hi @numeranazneen check whether this issue is now fixed

**Comment by raihan-mpower** [comment]
this issue is fixed..
