### ISSUE TITLE
Merging issues

### ISSUE THREAD

**Issue by dimasciput** [OpenSRP/opensrp-client#13]
I don't it's a good practice to merge everything into master before we really test it and satisfied with it. I think we need to revert back this commit → https://github.com/OpenSRP/opensrp-client/commit/249ea820bc6ce199a8bbee314c681bffd99d9d67

After that, if we want to merging branch to a master branch please do pull request and ask others to review it first.

**Comment by dimasciput** [comment]
@mberg , @ndisha , @raihan-mpower, @maimoonak

**Comment by raihan-mpower** [comment]
sorry my bad....i am reverting to the original version
