### ISSUE TITLE
Lock the Copy/paste option within the form, so that user can’t copy the 1st ID and paste in the 2nd. 

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#130]
The user has to type same NID/BRID twice in the FWNewHH and Census form for all eligible woman. But they are typing the ID once and copy/pasting it in the next field, which we shouldn't allow. Because if we allow them to do this, then the purpose of having these field twice will be violated. 

@cagulas @raihan-mpower

**Comment by koros** [comment]
@numeranazneen this issue should be fixed in the latest code, please try then let me know

**Comment by raihan-mpower** [comment]
fixed

**Comment by numeranazneen** [comment]
Checked. It's fixed. Thanks.
