### ISSUE TITLE
Not showing the alert message when exit form by pressing the back button (This occurred after we added the last data storing feature)

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#131]
@cagulas @raihan-mpower

**Comment by koros** [comment]
@raihan-mpower can you take a look at this, you can use this code as ref. https://github.com/OpenSRP/opensrp-client/blob/opensrp-indonesia-faster-forms/opensrp-indonesia/src/main/java/org/ei/opensrp/indonesia/view/activity/NativeKBSmartRegisterActivity.java#L281

**Comment by raihan-mpower** [comment]
this is fixed now , have placed alert dialog on back pressed
