### ISSUE TITLE
In the forms, ‘Required’ is showing when user is tapping on the required field, there is no use of showing this at that time

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#132]
Hi @cagulas as per your suggestion I checked in ona.io-enketo form, the problem is there as well. When I tap the field it's showing 'Required'. As it's not adding any advantage so I think we should remove this.

@raihan-mpower

**Comment by cagulas** [comment]
@numeranazneen I think I misunderstood you before.  So you're referring to the text "Required" that appears in the right margin when you tap into a required field, as in below screen shot?

![screen_shot_2016-01-12_at_1_29_39_pm](https://cloud.githubusercontent.com/assets/3488986/12272926/ebde1752-b930-11e5-985b-f0439fde46d4.png)

I had thought you were referring to the red alert box that surrounds the question.

This is an Enketo feature, so not sure there is anything we can do about this, and I'm not sure it's worth the trouble in trying to figure out how to remove it.  What would the added benefit be of removing it?  We have to weigh the options and see if the work to remove it is worth whatever benefit users would get out of it.  This is assuming it's possible to remove this, which I'm not sure of.  I would defer to @koros or @raihan-mpower

**Comment by numeranazneen** [comment]
@cagulas that's fine, this is not a very critical bug. Just curious to know if there is any reason to put it that way in enketo forms. 
The Field Workers actually wanted to see a message if the form is saved with missing required data. As we were highlighting the field only with a lighter shade of Red, that was not much convenient for the users. @raihan-mpower already worked on that requirement and added a message. So, I think now it's fine.

**Comment by cagulas** [comment]
@numeranazneen I don't know any specific reason for it.  To be honest, I never really noticed it before.  

Regarding adding the message for missing fields if user tries to submit the form, how was this done?  Do you mean by adding the **required_message** column to the forms?

**Comment by numeranazneen** [comment]
hey @cagulas can you please let me know how required_message column should work in the form. I added two columns required_message::Bengali and required_message::English, and put both Bengali and English message in the respective field (for the first question). When i tried to test in ona and submit the form without filing out the first question it still showed the english message.

**Comment by cagulas** [comment]
hi @numeranazneen I looked in the NewHH, Census, PSRF, Birth Notification form, and I can't find where you made these changes for me to check.  Let me know where I can check this.  Thanks.

**Comment by numeranazneen** [comment]
Oh ! sure.  I have uploaded that in ona (user/pass- dghealth/dghealth. The form name is 'গর্ভাবস্থা সনাক্তকরন ও নিবন্ধন ফর্ম' (PSRF). Thanks for looking into this. @cagulas

**Comment by cagulas** [comment]
Hi @numeranazneen thanks for sharing.  I was mistaken.  required_message is only supported in ODK right now, not Enketo.  Let's discuss this as a group and see if there's anyway we can support this.
