### ISSUE TITLE
Preloaded data Issue in Indonesia Visit forms

### ISSUE THREAD

**Issue by kercobo** [OpenSRP/opensrp-client#136]
hi @koros There is preloaded data from previous visit form in opensrp-indonesia  when opening new visit form, even there's no "shouldLoadValue": true in the  form_definiton.json.
can you help me investigate it?
Thanks 
please see here :
https://github.com/OpenSRP/opensrp-client/blob/opensrp-indonesia-faster-forms/opensrp-indonesia/src/main/assets/www/form/kartu_anc_visit/form_definition.json
and here : https://github.com/OpenSRP/opensrp-client/blob/opensrp-indonesia-faster-forms/opensrp-indonesia/src/main/assets/www/form/kohort_bayi_kunjungan/form_definition.json

**Comment by koros** [comment]
@kercobo alright i'll look at it then let you know, is the form new or its been there

**Comment by kercobo** [comment]
@koros its been there

**Comment by kercobo** [comment]
@koros The field team just finished doing testing on this issue, and from their report the problem is fixed.
thanks
