### ISSUE TITLE
Cleanup Thrive Pakistan directory

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client#141]
Clean up the Form directory for Thrive PK forms here. https://ona.io/opensrp/3234 . 
There are multiple instances of same forms as shown in image below 
![untitled](https://cloud.githubusercontent.com/assets/4829880/12507416/8ce28f82-c117-11e5-8a1c-71c8f37f726c.png)

Also it would great if forms are in separate folders so that we can distinguish b/w forms of vaccinator and lhw registery.. Moreover all form names should be in english and urdu both (rightnow its only urdu for some forms).

@cagulas @wajeeha

**Comment by cagulas** [comment]
I've created a new folder for the LHW forms and renamed the existing folder to be the Vaccinator folder, see below:

![screen shot 2016-01-22 at 9 10 56 am](https://cloud.githubusercontent.com/assets/3488986/12512768/23feb998-c0e8-11e5-9aef-a5ad74f1fd8d.png)

@wajeeha you can move the LHW forms into the new folder using the Move to option in the form dropdown menu:

![screen shot 2016-01-22 at 9 12 44 am](https://cloud.githubusercontent.com/assets/3488986/12512803/55b59aa6-c0e8-11e5-82b3-cb0786c1f7c2.png)

**Comment by cagulas** [comment]
It looks like this is done.
