### ISSUE TITLE
Create separate branch for Enketo code

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#145]
Currently all the custom changes are being done directly on the js file under the assets folder, OpenSRP Enketo code is needed such that all the custom code/modules specific to OpenSRP is maintained in the repo rather than the js assets folder as it is.

**Comment by raihan-mpower** [comment]
there is a repository called enketo-opensrp. You can put the most stable version of code there

**Comment by koros** [comment]
@raihan-mpower the one we have doesn't have the custom code, but i'll check if its possible to use that instead
