### ISSUE TITLE
Auto downloading of form_definition.json on client side

### ISSUE THREAD

**Issue by dimasciput** [OpenSRP/opensrp-client#17]
Refer to this issue : https://github.com/OpenSRP/opensrp-server/issues/29

**Comment by raihan-mpower** [comment]
same as this issue : https://github.com/OpenSRP/opensrp-client/issues/9

**Comment by ndisha** [comment]
thanks @dimasciput for the https://github.com/OpenSRP/opensrp-client/pull/25; closing this one!
