### ISSUE TITLE
Data not showing up on Followup forms

### ISSUE THREAD

**Issue by MohammadSafwan** [OpenSRP/opensrp-client#173]
In child and woman followup, the data is not pre-populated. Although, the data can be seen while debugging and is shown till the end. But due to some reason it's not showing up on the form. Maybe it's due to variable names being different.

**Comment by koros** [comment]
@MohammadSafwan will start working on it right after the sprint

**Comment by koros** [comment]
@MohammadSafwan copy over the changes to your current branch
