### ISSUE TITLE
Sort by age is not default sort in vaccinator apk

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#184]
When you first open the Woman Register in the vaccinator apk, it shows the register is sorted by Age, but it's actually not sorted by age until you manually sort by age.  

For instance, using demotest login, when you first open the Woman Register, the first woman listed is Aanchal, but if you sort by age, the list reshuffles and Jalthal is sorted on top.  I think the default sort is by woman's name, so it shouldn't say Age when you open the register.

**Comment by maimoonak** [comment]
Now sort by apha name is default..
