### ISSUE TITLE
Create new white/light blue OpenSRP logo

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#185]
As seen in https://projects.invisionapp.com/d/main#/console/5196543/147123901/comments/59104520

**Comment by rowo** [comment]
@maimoonak here you go. Let me know if you guys decide to change the name. I can change Vaccinator to anything. Longer term, we can explore something that the users might relate better to.

![vaccinator-logo](https://cloud.githubusercontent.com/assets/1584163/14386803/543995d8-fd74-11e5-93f3-1f77c9abeeb6.png)
