### ISSUE TITLE
Woman image pixelated

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client#186]
In vaccinator app woman avtar ia pixelated.

**Comment by cagulas** [comment]
As well as the OpenSRP logo for the "back" button on the register view.  Let's address both in this one issue.

**Comment by cagulas** [comment]
Any update on this?

**Comment by maimoonak** [comment]
Resolved back button issue in version opensrp-vaccinator-1.2.0.
Woman avtar is pixelated when made smaller. Its something to be fixed with image itself (I coud be wrong though).  
Full length image in Picture Manager:

![untitled](https://cloud.githubusercontent.com/assets/4829880/15882743/58684f48-2d5b-11e6-84d1-75a1ec0b936c.png)

Image with smaller size:

![untitled](https://cloud.githubusercontent.com/assets/4829880/15882775/9eb654b8-2d5b-11e6-9ace-bcb4e73b43b3.png)

Can we get a smaller picture with smooth edges and curves. Or maybe you can suggest any other fix.

**Comment by cagulas** [comment]
Please see this issue: https://github.com/OpenSRP/opensrp-client/issues/122

**Comment by maimoonak** [comment]
Thanks a bunch @cagulas . Its resolved on opensrp-vaccinator-1.2.1
