### ISSUE TITLE
Updates to vaccinator apk login screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#187]
![pk-vaccinator-login](https://cloud.githubusercontent.com/assets/3488986/14422381/41048992-ffdf-11e5-825d-6a58e0757ff7.png)

**Comment by cagulas** [comment]
The only thing left is to remove the space and make it "username" instead of "user name".  This issue can then be closed.

**Comment by maimoonak** [comment]
resolved in opensrp-vaccinator-1.2.0 in google drive (plz note that one shared in email is without this)
