### ISSUE TITLE
Move username/password fields up when keypad is opened in vaccinator apk

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#188]
As in the Bangladesh OpenSRP apk, when username or password field is tapped and the keypad opens, the fields are shifted up, see below.  This should be replicated on the vaccinator apk login screen.

I think @raihan-mpower implemented this on the BD apk, so please reach out to him.

![screenshot_2016-04-11-14-34-32](https://cloud.githubusercontent.com/assets/3488986/14423071/96756bb4-ffe2-11e5-997c-2e3a11cd7f02.png)

![screenshot_2016-04-11-14-34-41](https://cloud.githubusercontent.com/assets/3488986/14423036/6a90f0c2-ffe2-11e5-92a3-6d97eeeb318d.png)

**Comment by maimoonak** [comment]
resolved in opensrp-vaccinator-1.2.0 in google drive (plz note that one shared in email is without this)
