### ISSUE TITLE
Updates to vaccinator apk home page screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#189]
Please see page 08 of [style guidelines](https://drive.google.com/drive/u/1/folders/0B3wlsuQEG5hycUdQNXFkVFlrQ3M)

![pk-vaccinator-home](https://cloud.githubusercontent.com/assets/3488986/14423250/80008c3c-ffe3-11e5-815d-cfc81b3470e3.png)

**Comment by maimoonak** [comment]
resolved
