### ISSUE TITLE
Create UI for location dropdown modal

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#19]
This is primarily a change to help with scaling.  In Dristhi, locations up to the village level were pre-loaded into the form, but the ANM still had to select from her list of villages.  This meant we had to list every single village into the XLSForm for every single ANM using the app.  For Dristhi, this was already 100s of villages in the 'choices' sheet for 50 ANMs.  This will allow us to scale, in that locations can be passed dynamically to the app when it launches the modal, and we can choose at which point in the location hierarchy to start loading the health worker's locations, obviating the need to put any locations in the XLSForm itself.

**Comment by rowo** [comment]
@cagulas Since these locations can be passed dynamically does this also mean certain drop downs can be selected by default based on the health worker? Or are all of them required in sequence every time? 

Just to verify, according to the FWNewHH form, the sequence is select District, Upazilla (subdistrict), Union, Ward, then Mauza.

**Comment by cagulas** [comment]
@rowo yes, the implication is locations can be selected by default.  @raihan-mpower @dimasciput please correct here if I'm mistaken.  Please also provide more details on what input you'd like from Roger here, since you have an idea already of how this location picker would function in the app.  Thx!

**Comment by raihan-mpower** [comment]
![list_expandable3](https://cloud.githubusercontent.com/assets/6203919/7003356/ee1c862c-dc7a-11e4-8ae0-26e6e4c4416d.png)
me and dimas were thinking of something similar to the above in a dialog pop up.

**Comment by cagulas** [comment]
Looks fine to me.  @rowo any feedback?

**Comment by rowo** [comment]
@raihan-mpower So you are proposing this pattern follows down to five levels? The tree-table drill down might get a little crazy passed 3 levels. The advantage is it's clear where you are coming from though.

Since potentially a location might be drilled-down to a certain level (maybe Union level), maybe a breadcrumb made of drop downs would be good. Is being drilled-down to a certain level going to be a common scenario?

**Comment by cagulas** [comment]
For the Bangladesh context, their dropdown will look like this, if my understanding is correct:

Division --> District --> Upazilla --> Union --> Ward --> Sub-Block --> Mauza

Most of these can be pre-populated, however.  @raihan-mpower What is the catchment area of the health worker (i.e., which level in this hierarchy is the health worker's catchment area)?  Because the fields can be pre-populated down to whatever the health worker's catchment area is.  For example, if the health worker's catchment area is one Ward, then potentially she would only see fields for Sub-Block and Mauza (the other fields could be pre-populated and hidden, since they would never change).

Then all of these fields would be passed into the XLSForm as hidden fields, so that they can be included in the form submission to OpenMRS, where they will be mapped to the person's address fields in OpenMRS.

Is this understanding correct?

**Comment by raihan-mpower** [comment]
yes it is correct.......
And no location selecting from the forms

**Comment by rowo** [comment]
Cool, if the health worker only goes through a few levels that's great.

**Comment by raihan-mpower** [comment]
https://drive.google.com/open?id=0B9AKt4Ln_f4HQnpWb1dXSTFpTmM&authuser=0
this is how it might look like
@dimasciput i am done with the ui part , can you parse the location and put it into a tree form of similar category?
here is the file where you need to work on
https://github.com/OpenSRP/opensrp-client/blob/modalUi/opensrp-app/src/main/java/org/ei/opensrp/view/dialog/LocationSelectorDialogFragment.java
Line number 63-89 ....you will get an idea how i added the tree there.
if you could replace it with the user location tree of the user , it will work.

**Comment by dimasciput** [comment]
@raihan-mpower I'm done with the parsing location : https://github.com/OpenSRP/opensrp-client/commit/1adc43787c31849dc76f64cd0c978b8459b80f00
Could you try it? You not adding the library as a jar?

**Comment by raihan-mpower** [comment]
I did not add it as a jar as i had to make some changes and modification to inner classes.....plus it was only 4 classes.....

**Comment by dimasciput** [comment]
@raihan-mpower, I think it's better to using facade design pattern to wrap the library. 
facade design pattern : http://www.tutorialspoint.com/design_pattern/facade_pattern.htm

**Comment by raihan-mpower** [comment]
OK . But i also had an additional issue with the R of the library , it was giving a no class definition found error as it was not getting the R (resource references) when i was adding it as an external jar. I tried to add as a jar  and also tried adding as a maven dependency.

**Comment by dimasciput** [comment]
@raihan-mpower Maybe you need to build the maven so it can find the library.
