### ISSUE TITLE
UI updates for BD login screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#196]
![bd-login](https://cloud.githubusercontent.com/assets/3488986/14976481/b2c5ebc0-1114-11e6-8fa7-dfc00eeeab0c.png)

**Comment by raihan-mpower** [comment]
we need the topbar as the settings option is there in the device......................an empty top bar might look odd....but then again i can try and make it empty.

**Comment by cagulas** [comment]
Yeah, keep the top bar with the settings button, but without logo will be perfectly fine.  Right now, the double logo looks a bit odd and redundant.

**Comment by cagulas** [comment]
Looks great @raihan-mpower !
