### ISSUE TITLE
UI updates for BD household register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#199]
![bd-hh-register](https://cloud.githubusercontent.com/assets/3488986/14980652/9a08551e-1132-11e6-9fbc-41c7107d1aae.png)

**Comment by cagulas** [comment]
Link for new icon for back button: https://drive.google.com/open?id=0B4bsrvzHqGt-R28zOXUzaVFxV3M

**Comment by raihan-mpower** [comment]
@cagulas  the size of the no of elco column is large because of the bengali heading ...when i try to reduce the size of the column , the heading "no of elco" in bengali does not fit.
@numeranazneen  can elaborate....the location is visible in details and in location selector.
![screenshot from 2016-05-05 13 53 43](https://cloud.githubusercontent.com/assets/6203919/15038799/dc580a30-12c8-11e6-8ab4-77aa40e43b19.png)

**Comment by cagulas** [comment]
Ok, thanks for explaining. I guess that's ok then.

In the screenshot you provided, can you check the red color? It doesn't seem the same as what's in style guidelines.  Also, the text font color for the red reminder should be white, see the style guidelines on this as well.

**Comment by raihan-mpower** [comment]
@cagulas i used the exact drishti colors as it was on the theme , as per the guidelines the code is #d13f3f..................i used the same one here.

**Comment by cagulas** [comment]
Ok, then maybe it's looking off because the text font is black, not white. Once you change it to white, it will probably look ok.  Thanks for confirming.

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-09 13 50 49](https://cloud.githubusercontent.com/assets/6203919/15106775/5a40058e-15ed-11e6-8909-8aeedba4b0a5.png)
this is how the screen looks without bold fonts and only household due dates having bold fonts. Is this ok? I was wondering should i retain some of the text in bold?
@cagulas

**Comment by cagulas** [comment]
Nope, this looks great.  Please also see the remaining unaddressed comments in the original comment in this issue.

**Comment by cagulas** [comment]
@raihan-mpower Updates look really great!  Pls see a few remaining comments below:

![bd-hh-register](https://cloud.githubusercontent.com/assets/3488986/15141221/aff9e80e-16a7-11e6-8fa6-87610dbef5f3.png)

**Comment by cagulas** [comment]
Also, I still feel uneasy about the red exclamation point icon. It signals to me a health emergency, when in fact, it's just signaling that the health worker should take a picture of the woman's ID card. I'll create a separate issue for this, but would be good to think about a replacement for this.

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-10 19 16 48](https://cloud.githubusercontent.com/assets/6203919/15147739/efa6d85e-16e3-11e6-94ca-6e683ead086e.png)
this is how it looks like now ....with all the adjustments mentioned.

**Comment by cagulas** [comment]
Looks good, but please add a space between the comma and "Filtered"

**Comment by cagulas** [comment]
BEAUTIFUL!

![screenshot_2016-05-12-17-49-11](https://cloud.githubusercontent.com/assets/3488986/15218828/433488ae-186a-11e6-9b16-55a500cf00c9.png)

I see you're already applying the changes to the other registers as well, thanks!
