### ISSUE TITLE
updating enketo and improving date widget and supporting geo location

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#2]
the date widget is difficult to handle , we can aim to improve it and if possible make a native date widget appear in a dialog and get the feedback into the field instead of the current date widget.
Also enabling the geo location widget , which is currently disabled in the enketo-drishti

**Comment by ndisha** [comment]
Hey @raihan-mpower, on the current app, both the date and geo location widget work well, so can we close this issue?

**Comment by raihan-mpower** [comment]
@ndisha this was part of the pull request in issue2 , this has not been merged to master yet

**Comment by ndisha** [comment]
Closed by https://github.com/OpenSRP/opensrp-client/pull/72

**Comment by naveen-kommuri** [comment]
how to get the latest date widget, Is that a CSS?
