### ISSUE TITLE
Replace red exclamation icon with camera icon in BD app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#205]
The red exclamation point that currently signals that the FWA needs to snap a pic of the woman's ID card signals to me a health emergency or something much more severe than a simple reminder to snap a picture. I was thinking it can be replaced with a simple icon of a camera, perhaps in red font, using any number of the simple camera icons you can see here: https://thenounproject.com/term/camera/4303/

@rowo please suggest what might be good to use here.

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-10 19 16 48](https://cloud.githubusercontent.com/assets/6203919/15147718/da561992-16e3-11e6-806d-9b8a4a757b8e.png)
will this icon work ?

**Comment by cagulas** [comment]
@rowo what do you think?  Maybe a solid fill would be better, i.e., https://thenounproject.com/term/camera/766/ ??

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-11 19 30 43](https://cloud.githubusercontent.com/assets/6203919/15182552/eb1a9cf0-17ae-11e6-8353-ec415ccfdbd2.png)
this is the new one with a fill icon

**Comment by cagulas** [comment]
Awesome, this looks good.
