### ISSUE TITLE
UI updates to BD household details page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#206]
![bd-hh-details](https://cloud.githubusercontent.com/assets/3488986/15173680/254f0bac-1766-11e6-9234-6c5ce6dffc1f.png)

**Comment by raihan-mpower** [comment]
@cagulas the underline is to notify the use this is a link to the respective register

**Comment by cagulas** [comment]
See the STATUS column here from Dristhi, maybe something like this can be done to indicate which register status the woman has:  https://drive.google.com/open?id=0B4bsrvzHqGt-bGdFeTN2V2IzNFJ5QUpUSzZCWWpzYnRzYU0w

**Comment by cagulas** [comment]
You can even move the age to the same line as the woman name and put in parentheses, so it would look like:  Saju (40)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-12 20 20 27](https://cloud.githubusercontent.com/assets/6203919/15218056/f5dc3640-187f-11e6-99b7-e667cd0c80b6.png)
this is the current screen after adjustments

**Comment by cagulas** [comment]
![bd-hh-detail](https://cloud.githubusercontent.com/assets/3488986/15218278/e2209c3a-1867-11e6-9a67-e8c747d851e9.png)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-15 16 00 09](https://cloud.githubusercontent.com/assets/6203919/15273309/210ed5ec-1ab6-11e6-8e13-9b71b0fd2012.png)
@cagulas i made the changes as mentioned above

**Comment by cagulas** [comment]
Looks good.
