### ISSUE TITLE
UI updates for BD ELCO register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#210]
![bd-elco-register](https://cloud.githubusercontent.com/assets/3488986/15539595/1660d1a8-228c-11e6-9b97-2c998e83ebae.png)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-06-02 18 20 38](https://cloud.githubusercontent.com/assets/6203919/15746880/218fc858-28fa-11e6-8bf6-25846ece6c56.png)

**Comment by cagulas** [comment]
- [ ] Please add space between two HHID numbers
- [ ] Add a space between age and edge of box
- [ ] Unbold ID number
- [ ] Again, not sure what the green color signifies?
- [ ] Fix line spacing in PROFILE tab, looks like there's too much space between HHIDs and mauza

**Comment by raihan-mpower** [comment]
![elcoregisterlatest](https://cloud.githubusercontent.com/assets/6203919/15855027/e8375b7e-2cce-11e6-9f5f-658d36fba256.png)
