### ISSUE TITLE
UI updates for BD ANC Register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#212]
![bd-anc-register](https://cloud.githubusercontent.com/assets/3488986/15539928/0355d0d4-228e-11e6-97cf-60500b6dd34f.png)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-26 12 54 10](https://cloud.githubusercontent.com/assets/6203919/15566137/02eaf30a-2341-11e6-8d0c-c3650d0d6ed4.png)
same as birth notification , the anc reminder was anc reminder status and anc reminder due which were being cut off, so i have removed reminder from the title.

**Comment by cagulas** [comment]
Ok, thanks

**Comment by raihan-mpower** [comment]
![ancscreenshot](https://cloud.githubusercontent.com/assets/6203919/15746713/7f3081ce-28f9-11e6-8bc3-f87c02361845.png)

**Comment by cagulas** [comment]
- [ ] What does the green reminder signify?  Does this mean service was recently done?  If so, the color should be # 4FB45B
- [ ] For ANC DUE column, separate the ANC visit number from the due date. See how this was done in Dristhi [here](https://drive.google.com/open?id=0B4bsrvzHqGt-c1VtR3p0OFNmQms). So, for instance, for Maksuda, put "ANC 4" on one line and then put "2016-04-27" on the next line. Once you do this, you can make the ANC DUE column slightly narrower so that you can expand ANC STATUS column, which right now looks too squashed.
- [ ] The spacing of the lines in the PROFILE column doesn't look even. Too much space between HHID numbers and mauza name it seems.
- [ ] Please unbold the unique id number and EDD date and GA weeks.  Only the woman's name and due date reminders should be bold.
- [ ] The red checks and exes don't match the style of the rest of the page. You can use the ones from Dristhi, as seen in this [screenshot](https://drive.google.com/open?id=0B4bsrvzHqGt-VXM1M2VLZ3FiNWc)

**Comment by raihan-mpower** [comment]
@cagulas it means it was done and i used # 4FB45B as per UI guidelines. The color would seem a little off in my genymotion than it seems in a mac....but i used the same color code.

**Comment by cagulas** [comment]
ok, that's interesting, it looks very different, but as long as it looks ok on tablet, that's what matters.

**Comment by raihan-mpower** [comment]
![anclatest](https://cloud.githubusercontent.com/assets/6203919/15854930/5ef2aa30-2cce-11e6-8f82-d143ef4b1158.png)
this is the one with the fix

**Comment by cagulas** [comment]
Looks good. 

Couple small last things:
- Can you use a colon with past anc visit dates, so ANC1: 2015-10-31 instead of ANC1-2015-10-31?
- The ANC due and Birth Notification columns ideally should be the same size. Can we shorten the column heading "BIRTH NOTIFICATION" to something shorter, such as "BNF DUE" so that these two columns can be the same width?

**Comment by raihan-mpower** [comment]
@cagulas i brought this up with numera previously....even if we shorten the english heading the bengali is still long so we cannot really loose the space.

**Comment by cagulas** [comment]
Ok, that makes sense.

**Comment by raihan-mpower** [comment]
![ancreg](https://cloud.githubusercontent.com/assets/6203919/15921270/21f4b34c-2e42-11e6-9ba7-d00d905b4a7e.png)
added last mentioned changes.

**Comment by cagulas** [comment]
Ok, this is almost there.

- [ ] I think the spacing in the PROFILE column still looks uneven. For instance, it looks like there's too much space between Husband Name and HHIDs and HHIDs and Mauza name.
- [ ] Is there any specific reason that mauza name is all caps? I think if it's not all caps, you'd be able to see more of the name in the Profile column before it gets cut off
- [ ] Can you lower the bold font on "Sorted By: Due Status, Filtered By: All"? Sorted and Filtered by should not be bold, and Due Status and All can be bold, but reduce the font a bit, as it looks too big now.
- [ ] I noticed that BRID is aligned with woman's age, but NID seems to be shifted down slightly. Can you look at this?

**Comment by cagulas** [comment]
@numeranazneen is there anyway the Bengali label for the "Birth Notification" column can be shortened? It should really be the same width as the ANC Due column.

**Comment by cagulas** [comment]
Cannot change mauza from all caps for the time being.
