### ISSUE TITLE
UI updates to BD ANC details

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#213]
![bd-anc-detail](https://cloud.githubusercontent.com/assets/3488986/15540222/e6991b94-228e-11e6-8833-935e190b000d.png)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-05-26 15 34 27](https://cloud.githubusercontent.com/assets/6203919/15570344/6717f506-2357-11e6-9dde-885359374b72.png)
whenever anc is filled up an anc icon with values wpuld appear........pretty much like timeline icons used in drishti details page.......only some of the details values would not have icons? would you still want me to remove the icons? the icons were suppose to notify events in the patients survey.

**Comment by cagulas** [comment]
Ok, I guess that's fine, but the Summary and History sections don't seem to be categorized very well.  For instance, Number of stillbirths might be better placed in History.  It just looks a tad off when there are some icons in Summary and some don't have it.

**Comment by raihan-mpower** [comment]
alright i shall move them to the history section

**Comment by raihan-mpower** [comment]
the fields are blank as they are dependent on some forms which are yet to be filled or are not applicable in some cases.

**Comment by cagulas** [comment]
Ok, should they have a 'NA' or something similar until they are filled?

**Comment by raihan-mpower** [comment]
@numeranazneen @klzeller any comments regarding this?

**Comment by raihan-mpower** [comment]
![ancdetailsscreenshot](https://cloud.githubusercontent.com/assets/6203919/15746627/2b3f81dc-28f9-11e6-955c-8f6aa0a3da41.png)

**Comment by cagulas** [comment]
Looks good.
