### ISSUE TITLE
UI updates for BD PNC register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#214]
![bd-pnc-register](https://cloud.githubusercontent.com/assets/3488986/15540371/9beff576-228f-11e6-835d-a4cef13c80ec.png)

**Comment by raihan-mpower** [comment]
![pnc register](https://cloud.githubusercontent.com/assets/6203919/15746456/6a07cd30-28f8-11e6-81ac-9234d4f141b3.png)

**Comment by cagulas** [comment]
Points 6, 7, 9 are still not addressed.

**Comment by raihan-mpower** [comment]
![pnc register new](https://cloud.githubusercontent.com/assets/6203919/15856847/06488204-2cda-11e6-9734-3617ae985fef.png)
