### ISSUE TITLE
UI updates for BD PNC details

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#215]
![bd-pnc-details](https://cloud.githubusercontent.com/assets/3488986/15540481/40bd3672-2290-11e6-95f4-ad8c696ddc3f.png)

**Comment by raihan-mpower** [comment]
![pnc details](https://cloud.githubusercontent.com/assets/6203919/15746408/439bb602-28f8-11e6-8ea8-11be8e5e7b21.png)
UI changes

**Comment by cagulas** [comment]
Change "DATE OF OUTCOME" to "Date of Outcome"
Capitalize "birth" so it's "Live Birth"
Change "Type Of Delivery" to "Type of Delivery"
"Summary doesn't seem to be centered in the grey heading space

**Comment by raihan-mpower** [comment]
![pnc details screen](https://cloud.githubusercontent.com/assets/6203919/15856027/021e221a-2cd5-11e6-8490-7aa9ea256e1a.png)
