### ISSUE TITLE
UI updates to BD Child Register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#216]
![bd-child-register](https://cloud.githubusercontent.com/assets/3488986/15540570/cd5760bc-2290-11e6-925b-acbe0aca43eb.png)

**Comment by raihan-mpower** [comment]
![childregister](https://cloud.githubusercontent.com/assets/6203919/15746358/080ffcec-28f8-11e6-956b-08c12e7cb378.png)
UI with changes

**Comment by cagulas** [comment]
Looks great.
