### ISSUE TITLE
UI updates for BD Child details

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#217]
![bd-child-details](https://cloud.githubusercontent.com/assets/3488986/15540682/687ef186-2291-11e6-8abe-e1a3630e72d6.png)

**Comment by raihan-mpower** [comment]
![screenshot from 2016-06-02 19 23 34](https://cloud.githubusercontent.com/assets/6203919/15746332/ec0a1f82-28f7-11e6-81e1-ce012e39fc36.png)
ui now with changes

**Comment by cagulas** [comment]
Looks great.
