### ISSUE TITLE
Update in MIS Census/ELCO

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#219]
MIS Census:
* Form Name in Bengali- জনসংখ্যা হিসাব ছক
* Moved constraints from constranitMessage field
* Moved Required=' yes' from relevant field
* Moved appearance (numbers, field-list) from default field

MIS ELCO:
* Form Name in Bengali- দম্পতি ছক
* Corrected the Bengali in choices tab-
* Bought by Woman মহিলা নিজে কিনেছিলেন, Other source অন্যান্য মাধ্যম

**Comment by numeranazneen** [comment]
@asifur77 @sohelsarder

**Comment by raihan-mpower** [comment]
this is done
