### ISSUE TITLE
UI updates to PK profile screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#221]
![screenshot_2016-06-03-10-12-22](https://cloud.githubusercontent.com/assets/3488986/15771789/b544cadc-2975-11e6-8233-7d93d3cf4bbd.png)

**Comment by cagulas** [comment]
For the back button, please reference the BD app. It should look exactly like theirs: https://github.com/OpenSRP/opensrp-client/issues/215

**Comment by maimoonak** [comment]
Resolved all in opesrp-vaccinator--1.2.0 except alignment of today. A new issue created #226
