### ISSUE TITLE
UI updates to PK home screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#223]
![pk-home](https://cloud.githubusercontent.com/assets/3488986/15772056/8e016ff0-2977-11e6-8e86-87ece7efa625.png)

For the profile icon, maybe use [this one](https://www.google.com/search?q=profile+icon&rlz=1C5CHFA_enUS549US549&espv=2&biw=1408&bih=750&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiF8f70p4vNAhVEVRoKHQL0B6YQsAQIGw#imgrc=6shJLXaALRT5cM%3A) instead.

**Comment by maimoonak** [comment]
Resolved in opensrp-vaccinator-1.2.0
