### ISSUE TITLE
UI updates to PK profile screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#224]
![pk-profile](https://cloud.githubusercontent.com/assets/3488986/15772348/503a2714-2979-11e6-9d3c-c26c971b8528.png)

**Comment by maimoonak** [comment]
Resolved all except:
- Icon is now pencil only which is to show that this pic can be edited.
- Comma in address would never be see as House / Address line 1 is mandatory. This entry is from pre-release version
- Today is not left aligned as our IDs are 14 digits. Not sure how to make it left alignedwith varying length.

**Comment by cagulas** [comment]
So you're saying instead of the woman avatar image, it's just a pencil image? Not sure if this would look right and think having the woman avatar image would be better. Can you share the apk to take a look, either that, or you can paste a screenshot of the updated page here?

**Comment by maimoonak** [comment]
Sorry, I meant that the pencil is without white background on woman image.

![screenshot_2016-06-08-08-29-36](https://cloud.githubusercontent.com/assets/4829880/15881918/631ffe16-2d53-11e6-8123-5762342348f6.png)

**Comment by maimoonak** [comment]
A new issue created for Today alignment #226

**Comment by cagulas** [comment]
Looks beautiful.
