### ISSUE TITLE
make changes to readme file to add demo login and change logo url

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#23]

**Comment by maimoonak** [comment]
@raihan-mpower I have changed the admin password. Would be sharing it with each core dev separately again. The admin user of openmrs could be very destructive if gets into hands of naive user. Ideally we should not share credentials publicly. But incase it is really necessary we should create a user with less privileges. We would also make it sure for our server side code where properties file needs admin user credentials.
