### ISSUE TITLE
ELCO Register- If any one of an eligible couple dies or migrates to another place it should go out of the list

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#249]
If the Woman Dies, remove the woman both from HH Inhabitants Page and ELCO.
If the Woman Moved, remove the woman from ELCO, but keep her in HH Inhabitants page.
If the Husband Died, remove the woman from ELCO, but keep her in HH Inhabitants page.

@cagulas @klzeller @sohelsarder

**Comment by raihan-mpower** [comment]
can you mention the form values that change in each case
