### ISSUE TITLE
When a woman is found to be pregnant, it should remain in the ELCO list as well

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#250]
Currently if a woman is found Pregnant in ELCO, she moves to ANC. But as per this requirement the woman should be in both ELCO and ANC. Keep the color of the last submitted PSRF Green. In HH Inhabitants page, show the current register of the woman as ANC.

@cagulas @sohelsarder @klzeller

**Comment by raihan-mpower** [comment]
please change logic of form to have is_eligible = 1 when elco is selected to be pregnant
