### ISSUE TITLE
App performance too slow for 1000 above data

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#256]
Check the user: anjuman 
URL: 27.147.129.50:9979/ 192.168.19.55:9979
Let me know to get her Password

**Comment by numeranazneen** [comment]
@cagulas @sohelsarder

**Comment by cagulas** [comment]
Why are there two urls?

Can you be more specific? What in particular is slow about the app? She has 1000 records in a single register or across all registers?

**Comment by numeranazneen** [comment]
1st one is Real IP, second one in Local IP (for mPower's network usage)

Every functionality is slower for the user. It takes time to response after every tap. She has ~1000 in either HH/ELCO. I'll verify and let you know.

**Comment by cagulas** [comment]
And just to confirm, the version of OpenSRP that she's using has the latest cursor adapter and also the faster enketo forms?

**Comment by numeranazneen** [comment]
Yes

**Comment by cagulas** [comment]
Are there any other health workers with over 1000 records? If so, how is the performance on their tabs? Did this performance issue come up when you did the benchmark performance testing when the curser adapter was first implemented?

**Comment by raihan-mpower** [comment]
@numeranazneen please check with the latest build after @keymane worked on the cursor loaded , i believe this issue is resolved.
