### ISSUE TITLE
use of cursor loader to make cursor adapter operations smooth

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#259]
https://developer.android.com/training/load-data-background/setup-loader.html
Cursor loader may solve database access issues while syncing which slows the app down. Looking into cursor loader may help us resolve some of the register sluggishness

**Comment by maina** [comment]
This issue should also try to fix the occasional error in logs console:
Finalizing a Cursor that has not been deactivated or closed. database = /data/data/org.ei.opensrp.mcare/databases/drishti.db, table = null, query = ...... alnet.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

**Comment by raihan-mpower** [comment]
this looks solved.
