### ISSUE TITLE
[EC reference app] Delete first two null entries in PK vaccinator app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#281]
In the demotest login for PK vaccinator app (pointed at Ona server) there are two null entries at the top of the register (see below). Please delete these two entries.

![screen shot 2016-10-13 at 4 29 56 pm](https://cloud.githubusercontent.com/assets/3488986/19350994/af32ad80-9162-11e6-95a5-b3295f98b8b6.png)

**Comment by keymane** [comment]
@cagulas I've deleted the records but you may need to clear data or re-install the app.

**Comment by cagulas** [comment]
Awesome, I can confirm they're gone.
