### ISSUE TITLE
BZ1 - ￼￼Ability to record that an immunization was given during an outreach campaign

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#297]
This implies needing to have the ability to set the location of where the vaccine is happening.  This is a pretty common use case for most vaccine programmes.

@rowo to keep the fast input we'll need to create an ability to set the location state of the user.  I'm imagining something where we always show the users location and then there is some type of slide interface to set it and perhaps a few other key settings.

We might want to have it where it defaults back to the users health facility after a day.  If we wanted to get fancy later we could use GPS to determine if they are outside of their facility which would prompt them to switch but that would be beyond initial scope.

Here is a slide-up library that could potentially be useful or provide design inspiration.

https://github.com/mancj/SlideUp-Android

**Comment by cagulas** [comment]
Location hierarchy will be loaded into OpenMRS. The PATH team is working on the location hierarchy in this [spreadsheet](https://docs.google.com/spreadsheets/d/1RpB_gNOwFBw-ZbuA_x7hylUo3X8lMhok-I2mnXKGZpU/edit#gid=1567641917). Once our OpenMRS instance is set up, I'll start adding these locations in, so please let me know when it's up. In brief, the location hierarchy for selecting vaccine location will be the health facility name or zone number. For eg. Victoria Falls clinic has two zones, while Linda clinic has five zones. 

So in the register view, the default location will be the clinic name. During outreach sessions, though, she will be able to tap on the name of the clinic and select the appropriate zone from the list. For example, a nurse from Linda clinic can leave Linda clinic selected if giving vaccines at the clinic, or if she goes to Zone 5 to give vaccines, she can tap on Linda clinic and select Zone 5 from the dropdown. Whichever location is selected, that will be the encounter location in OpenMRS.

The next day, the location should default back to the clinic name.

**Comment by cagulas** [comment]
@rowo Will you be providing a mockup showing this dropdown? I think they should be able to do the dropdown in both the register view as well as the vaccine card. The location should persist until the next day, when it defaults back to the clinic name (say at midnight).

**Comment by rowo** [comment]
@cagulas Do you have a screenshot of the dropdown from the other app? If so we can just use that — I wasn't planning on creating mockups of something that already exists.

Location selection comes from the top bar where in the mockups it says "Linda Clinic". Clicking that will open up the dropdown. There won't be a "default back to clinic name"... we'll just leave it as where it was last done and train for that. If we run into issues with this we can look at options.

**Comment by cagulas** [comment]
@rowo The dropdown is really for a hierarchy, where you select from multiple levels, each level further indented than the last. There is no hierarchy with this dropdown, it's only a list of zones within the clinic's catchment area, so not sure how it should look. It would be helpful to see this. Would it just look like the dropdown from a multiple choice question in the form?

**Comment by rowo** [comment]
I think a [simple dialog](https://material.io/guidelines/components/dialogs.html) would work. It's kind of like a dropdown: https://projects.invisionapp.com/d/main#/console/10214563/218832683/preview
