### ISSUE TITLE
BZ1.1 - Maintain a list of vaccines and other drugs that are provided in their country

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#298]
App will need to contain the vaccines and drugs specific to Zambia.

Requirements needed

- [x] confirm with PATH what vaccines and schedules are needed in Zambia @cagulas

**Comment by cagulas** [comment]
The list of vaccines and their schedules is finalized and listed [here](https://docs.google.com/spreadsheets/d/1qB7kVl5M9CpTw8m4VRE5TjRpGdK996yXDWnHZdysWD0/edit#gid=0).
