### ISSUE TITLE
BZ1.3 - Support real time data entry validation and feedback to prevent data entry errors from being recorded.

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#299]
This should already be supported with forms and vaccine quick forms.  We should review and confirm if there are any potential required use cases not supported.  Probably don't want to add beyond what we currently support.

**Comment by cagulas** [comment]
All data constraints required for the app are listed in the data dictionary [here](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1356611293). Please see the **Constraint(s)** column in each tab. All constraints are currently supported with existing xlsform constraints. The constraint message shown in the **Constraint(s)** column can be used as the constraint message shown in the app.
