### ISSUE TITLE
Open srp package refactoring

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#3]
change package names from Org.ei.drishti to Org.ei.opensrp and also change module names

**Comment by raihan-mpower** [comment]
done in the following branch
https://github.com/OpenSRP/opensrp-client/tree/OpenSrp-Client-Refactor

**Comment by ndisha** [comment]
This issue is blocked by pending pull requests yet to be merged to master and others issues whose code is in other branches and not on master...

@raihan-mpower  @dimasciput lets close on the blockers

**Comment by ndisha** [comment]
is this issue closed by #28?

**Comment by dimasciput** [comment]
@ndisha , Yes it is.

**Comment by ndisha** [comment]
Thanks @raihan-mpower @dimasciput; closing this!
