### ISSUE TITLE
BZ1.2a-c - Define the ideal age within the national vaccine schedule at which children should receive vaccines (support two constraints, below)

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#302]
We already do this with our schedules. One of the requirements PATH requested is to be able to override - ie) give a child a vaccine if the app says they are too old or too young (or vaccine not spaced enough from last one). The app should provide a warning message, however the provider can override the message to proceed anyway. We need to explore modifying the quick database entry UI to throw a flag but allow them to override. If they do override, we can provide a list of options in a pull-down to select from of the reason why to provide the vaccine. 

a) The minimum age before which a child is not eligible for a certain dose.
c) A max time that needs to pass between dose of the same vaccine.

Requirements to check @cagulas 

- [x] What are the conditions where this will happen
- [x] Get list of reasons they would want to record for giving vaccine despite warning

**Comment by cagulas** [comment]
Combined with BZ3.5 In the event a provider overrides a warning message to provide a vaccine out of the recommended range, a reason should be given (based on a drop down list of choices, or a free text “other”).

**Comment by cagulas** [comment]
Vaccine override can only occur 7 days or less before the vaccine due date (for all vaccines). In the app, the reminder button can turn from grey to light blue (upcoming) 7 days prior to due date. While the reminder button is grey, it cannot be tapped. At 7 days prior to due date, the button will turn light blue and become tappable. The vaccine modal will open showing the warning that the vaccine is not yet due, but the health worker can give the vaccine anyway, but must select an override reason. The warning message and override reasons are listed in the data dictionary, [Vaccine Override](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1356611293) tab.

@rowo are you providing a mockup for this?

**Comment by rowo** [comment]
The "grey" button is just a white non-button: https://projects.invisionapp.com/d/main#/console/10214563/217470550/preview.

Here's the "override warning": https://projects.invisionapp.com/d/main#/console/10214563/218199050/preview. I shortened the label some.
