### ISSUE TITLE
BZ1.6 Enter historical data upon first visit to health centre (e.g. doses given at birth)

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#305]
OpenSRP already supports this via a registration enketo form. 

- [x] Need list of historical data that would be captured.

**Comment by mberg** [comment]
That's fine.  Part of the reason for doing this is to flesh out where we
need specific requirements.  So we should add a needs requirement asking
specifically what historical data could potentially be captured.

**Comment by cagulas** [comment]
All historical data that needs to be captured is in the [birth registration form](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0) fields. In addition, once the child is registered, the nurse can immediately go into the child's vaccine card and record vaccines given (i.e., birth doses), so the app will need to be able to support offline registrations and immediate entry of birth doses.

**Comment by mberg** [comment]
We are separating the client registration from the vaccine card.  So they will just register and then do the vaccine after so these don't need to be tied together.
