### ISSUE TITLE
BZ2.3 Uniquely identify every person in the registry

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#314]
- [x] From Path, we need the list of IDs that will be captured for each child, when they'd be captured (i.e., at birth, after birth certificate issued, etc.) and their level of uniqueness (universally unique, nationally unique, etc.). And also whether it is used by health worker to ID a child (i.e, whether to put in register view or profile view).

**Comment by cagulas** [comment]
Same as BZ2.5 Allow a record to have multiple alternate IDs

**Comment by rowo** [comment]
They don't use qr/barcodes (yet), correct?

**Comment by cagulas** [comment]
Correct, and they will not be using them. Mandy commented in the wiki on this req about having the system provide unique IDs.

**Comment by cagulas** [comment]
Update from the project kickoff meeting is that QR codes might be used after all. They are looking into printing costs. If QR codes are used, they would use the IHS QR code generator tool to create, print, and cut the QR code stickers before delivering them to the health facilities. The QR sticker would be affixed to the U5 card when it is issued to the child. If this is the case, we would only need to host an instance of the IHS QR code generator app and database (the database stores the QR codes that are generated).

If they do not use QR stickers, the system would need to automatically generate a unique ID and assign to each child in the birth registration form. We would use the OpenMRS ID gen module for this. Indonesia team is currently using this, so we can discuss with them. The format of this ID would be 6 random digits, followed by a check digit, so 7 digits in total.

**Comment by cagulas** [comment]
Marking as blocked until we hear from Path about whether QR codes will be used or not.

**Comment by cagulas** [comment]
System needs to generate a random 6 digit + 1 check digit (7 digits total) unique ID for each child. This will likely be done in OpenMRS IDGen module and batches of IDs will be synced to each device. This ID number will be assigned to each child during birth registration and be displayed in the form as the `ZEIR_ID` number. 

Also, QR codes will need to be supported. This will be a supplementary unique ID that PATH team will be testing out in one district.
