### ISSUE TITLE
BZ3.4 Support an audit trail when event records are merged

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#321]
- [ ] Would this only be handled in OpenMRS? If not, what parameters would be used to identify possible duplicate events? What mechanism would be used to merge them?
- [ ] Similar to BZ3.3, need to identify where audit trails would be viewed.

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#82
