### ISSUE TITLE
BZ4.9 The system should help them determine which children are due or overdue at any given time

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#339]
Handled through schedules.

- [x] Need schedule definitions
- [x] Need color schemes to show when vaccines are due

**Comment by rowo** [comment]
Are we going to refine the interface around this at this time, i.e. do we need a defaulters list or easy access button, or is a register filtered by overdue enough? The former could be combined as an indicator (total number of due/overdue) as useful feedback to the user — it would make it explicit what kind of change the project is trying to make happen.

**Comment by cagulas** [comment]
They removed defaulter's list from the requirements. This is just the reminders for due and overdue immunizations. Not sure what you mean by "easy access button".

I do like the idea of an indicator in the register itself showing how many due and overdue.

**Comment by cagulas** [comment]
"Due" children will appear as a dark blue reminder, while "Overdue" children will appear as a red reminder in the register view and child vaccine view, according to Roger's mockups.

@rowo on the overdue/due view, could we show the number of each? I.e., number of due children and number of overdue children?

**Comment by rowo** [comment]
https://projects.invisionapp.com/d/main#/console/10214563/217469973/preview

I think total number and number overdue is good. Total is shown in parenthesis at the top title.. it would tell you how much stock you should plan to bring perhaps. Overdue shows who and how many you have to focus on. I'm not sure what just a "due" total alone could tell you.

**Comment by cagulas** [comment]
Ok, this is great.
