### ISSUE TITLE
BZ6.2 Ability to prompt the user that the new vaccine is a duplicate

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#345]
- [x] Need to confirm use case for this. Will providers be able to mark a vaccine was given twice? This is prevented in current app, because already-received immunizations are not allowed for selection again.

**Comment by cagulas** [comment]
The only time this would happen is for BCG. After 12 weeks, if no BCG scar is present, the health worker gives BCG again. @rowo need UI for this.

In other cases, it might happen where the health worker marks a child's vaccine was given, but then the stock runs out before the child receives that vaccine. This would be handled using the "undo" option in the app.

@rowo we don't currently see an "undo" option in the given vaccines. I think this would need to be added or some mechanism for editing the vaccines.

**Comment by rowo** [comment]
Undo is https://projects.invisionapp.com/d/main#/console/10214563/218152522/preview. We could handle BCG in the same way (add both Redo and Undo buttons). Alternatively, show a BCG button 12 weeks after BCG is first given where if you click it you can dismiss or give.
