### ISSUE TITLE
BZ6.4 Allow searching for children based on family relationships or demographic

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#347]
For demographics, I think this is same as 3.1, but for family relationships, this might be different.

- [x] What family relationships would be marked in the application? I.e., if the app only registers children, then does this mean only marking sibling relationships? Are others included?

**Comment by mberg** [comment]
I think it might mean an advanced search where you can plug in a mothers
name.  Right now I'm curious if the full-text search covers the mother's
name if that's one of the demographic details of the child.

I can see a scenario where you search for a mother and find the multiple
children she has.

**Comment by cagulas** [comment]
You can search for the mother/guardian name in the advanced search. If multiple children are registered to the mother, they would appear in the search results.

Additionally, the child's siblings are shown in the child's profile view.
