### ISSUE TITLE
Shared Preferences to manage URL and other configurable properties

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client#36]
In mobile client we always have to rebuild application whenever url of server changes. In one of our demo app we added a shared preferences settings form on login page where user can configure url before logging in. It helped us in changing url without building app for localhost and test server again and again.
This would also help in managing Configurable properties in shared preferences instead of file in assets.

@ahmedihs is interested in adding this feature to OpenSRP client.

Please provide your feedback if there are any concerns or if this is welcomed feature.

@raihan-mpower @ndisha @dimasciput

**Comment by sohelsarder** [comment]
I think it is very nice idea, it would add flexibility  of client to switch from one server to another which is very common case specially at inception period of a project.

**Comment by raihan-mpower** [comment]
I have already done this with one of our projects....i think this is an important feature, @maimoonak @ahmedihs can make the required changes to https://github.com/OpenSRP/opensrp-client/blob/master/opensrp-app/src/main/java/org/ei/opensrp/DristhiConfiguration.java file by adding and retrieving from shared preference , and add a shared preference activity/dialog, i shall link it to onoptionselected in the login activity.

**Comment by maimoonak** [comment]
@ahmedihs Can you share a diagram and breakdown of tasks for the feature?

**Comment by raihan-mpower** [comment]
this is done and is added to the master
