### ISSUE TITLE
Review icons and logos for OpenSRP BD client app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#37]
https://drive.google.com/drive/u/0/folders/0B4bsrvzHqGt-UFkybjRKcTRFSm8/0B4bsrvzHqGt-eWh1WHg4R3gyeGc/0B4bsrvzHqGt-fkdaWlRLUXh5Y1J4ajkyY0VoM3VlQl9CZUFPMzlJMmVCT0cyQXlLa2p2dUk/0B4bsrvzHqGt-flNobDdhWEpXUGRTeGFESlJQcmVVUFJkTUpRa2dsamRvRjBSWk9ROVNLSTA  

@rowo assigning to you for review.  Have added the images to the thrive google drive folder (link above).

**Comment by rowo** [comment]
@cagulas where do the icons that are in that folder show up? I recognize some of them, but SMS, GoB, Thermometer, female, male don't show up in the screenshots you took from the app. The others I'm assuming are the register "book cover" graphics, which can be up to the sites.

**Comment by cagulas** [comment]
Yes, those will be the book cover graphics.

The others are in the [mockup pdf](https://docs.google.com/file/d/0B42mFq702to6VEpIdFhVanNiT0U/edit) that Numera created, with the exception of the SMS and GoB icons.  The intention, I assume, is to replace the Dristhi female icon with these male/female icons.  The thermometer is on the PNC details page.  Pls take a look.  It is vertical, but was wondering if a diagonal thermometer might be needed given the space?  

The GoB logo has to go on the home page somewhere.

I will check with Numera as to what the SMS icon is for.

**Comment by rowo** [comment]
From the email it looks like Numera expects new versions of these and the icons were just for the mockup. So I'm not actually sure what this issue is for.

**Comment by rowo** [comment]
Talked to Carolyn. Purpose: look through and determine if any of the icons need to be redone. If so, put them into https://github.com/OpenSRP/opensrp-client/issues/38

**Comment by rowo** [comment]
Reviewed and added to #38
