### ISSUE TITLE
Visual assets updates

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client#38]
Logos
- [x] logo for login screen
- [x] logo for home screen

Icons
- [x] icon for "return to homescreen" button

Avatars
- [x] Male
- [x] Head of household

**Comment by raihan-mpower** [comment]
icon for additional registers like household , death

**Comment by raihan-mpower** [comment]
we would need additional logos like
male logo
household head logo

**Comment by cagulas** [comment]
@raihan-mpower these are included in #37  with the exception of death icon...is there a plan for a death register...haven't seen one anywhere?

**Comment by rowo** [comment]
I have to add to this list all of the icons they are missing and used as placeholder. Was under the assumption the icons in the folder were intended by BD as their final ones, which is not the case.

**Comment by rowo** [comment]
@raihan-mpower here are some updated items, logos mainly. I split up the other items into #52 and #51, which will be done later.

**Login**

![opensrp-login](https://cloud.githubusercontent.com/assets/1584163/7823291/841e9f74-03c8-11e5-8aee-829c595b7068.png)

![opensrp-login-logo](https://cloud.githubusercontent.com/assets/1584163/7823292/86146c82-03c8-11e5-9742-c6b339e3b155.png)

**Home**
I don't' think the logo in the middle is necessary, just the top left. But if people really want it, we can add it back in, though I have to explore it a bit more.

![opensrp-home](https://cloud.githubusercontent.com/assets/1584163/7823298/91c7b23c-03c8-11e5-8254-1b3cdf0b2d98.png)

![opensrp-home-logo](https://cloud.githubusercontent.com/assets/1584163/7823310/9fafab98-03c8-11e5-8dff-1a64d9df3803.png)

**Registers**
This is just about the "back to home" button

![opensrp-register-back](https://cloud.githubusercontent.com/assets/1584163/7823341/d44e8374-03c8-11e5-8107-141248e1bf03.png)

![opensrp-register-back-icon](https://cloud.githubusercontent.com/assets/1584163/7823344/d87b3c30-03c8-11e5-8029-bfe46c3481fe.png)

**Comment by rowo** [comment]
And the male avatar to match the woman one:

![avatar-man](https://cloud.githubusercontent.com/assets/1584163/7823458/975810c4-03c9-11e5-9ea8-643ad274dc6a.png)

**Comment by raihan-mpower** [comment]
@rowo i would also need logo for the household register........by that i mean the logo on top of a booklet with gradient as it is in drishti  or current open srp app

**Comment by raihan-mpower** [comment]
![register_ec](https://cloud.githubusercontent.com/assets/6203919/7823646/d2263fd2-041e-11e5-9646-d1338d1786b3.png)
similar to this with household icons

**Comment by rowo** [comment]
@raihan-mpower this work?

![hhregister](https://cloud.githubusercontent.com/assets/1584163/7824259/8bd6e9a4-03cf-11e5-9526-752d56a1b0ae.png)

**Comment by raihan-mpower** [comment]
yeah fair enough i also have an additional concern

**Comment by raihan-mpower** [comment]
![login](https://cloud.githubusercontent.com/assets/6203919/7824307/c3140920-0423-11e5-8470-881d7aeb7b20.png)
there is an action bar in the login screen now ....this is in homescreen too....do you have any feedback regarding the color

**Comment by rowo** [comment]
@raihan-mpower right now it's #2b475e

**Comment by cagulas** [comment]
@raihan-mpower if you see Roger's login design up above, there is no top bar that says OpenSRP.  Can you just remove this bar completely?  

![login](https://cloud.githubusercontent.com/assets/3488986/8012320/960792b8-0b8e-11e5-9913-00ebdf6a732e.png)

Also, the HH Head male icon looks pixelated in the latest apk.  Can you look into that as well?

**Comment by raihan-mpower** [comment]
@cagulas the bar is required for the options menu, right now this bar allows the preference feature......it allows to go to the settings and change server url.......
#36 refers to this. In order to show menus , the action bar needs to be visible for settings option to appear, we can change its color if necessary.

**Comment by cagulas** [comment]
Ok, is the settings option currently in the action bar, or has this not been added yet?  I didn't see it last time I looked.

You can change the action bar color to #2b475e, which should also be the current color of the action bar in the homescreen.

**Comment by raihan-mpower** [comment]
@rowo do you have any suggestions for a loading image placeholder? in case of households that have images , it would look better to have an image loading placeholder than just a male placeholder as it shows no difference between ones with image and ones without it.

**Comment by rowo** [comment]
@raihan-mpower why is there loading time? How long does it take to load something? We could do a greyed out version of the male/female images with a loader on top. Can we do GIFs?

**Comment by raihan-mpower** [comment]
well loading time for images as they are processed...it takes 2-3 seconds....these are shown from the device but are stripped down in size a little bit........we cannot do gifs.........i guess greyed out version might work.......

**Comment by rowo** [comment]
Alright. I will make something for that 2 second period that indicates a photo will be loading. Alternatively you could do it [Pinterest style](http://blog.embed.ly/post/51071740487/pinterest-colored-background-placeholders).

**Comment by rowo** [comment]
@raihan-mpower do you think these will work? Three dots = loading.. does that work in your context?

![female-loading](https://cloud.githubusercontent.com/assets/1584163/8370227/c2d08cc8-1b92-11e5-8a77-4a3f1c24a0b5.png)
![male-loading](https://cloud.githubusercontent.com/assets/1584163/8370228/c2d12c0a-1b92-11e5-979e-ef4b1bb88a07.png)

**Comment by raihan-mpower** [comment]
yea this would do....in my context....the pinterest style would be an expensive process...
