### ISSUE TITLE
Native form for birth registration with widgets

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#382]
Add the following changes:
- [x] Date picker (format should be DD/MM/YYYY)
- [x] Location picker (used in `Home_Facility`, `Birth_Facility_Name`, and `Residential_Area` fields). 
- [x] Add support for skip logic
- [x] Pre-populate ZEIR ID field with an OpenMRS unique id. The field should be read-only #406 
- [x] Photo widget and profile image upload to the server #403
- [x] QR code scanner - This will be part of the ZEIR field so that users can scan a new id to override the one already assigned by the system.
- [x] Required fields
- [x] Data constraints and error messages
- [ ] Lookup - check for duplicate records, check for mother matches
- [ ] Create mother entity and relationship mappings within form (i.e. create mother entity (DOB needs to be automated to 01-01-1960 if left blank), create relationship mappings in OpenMRS for parent/child and sibling/sibling, if relevant)
- [x] Saving #403 
- [x] Editable, non-editable fields (after birth reg form is submitted, only some fields will be editable in the detailed view
- [x] Calculations - be able to calculate and display age in form from DOB
- [x] Ensure all question types are supported: Text, Integer, Decimal, Select one, Select multiple
- [x] Is metadata capture possible? E.g., IMEI, start time, end time, phone number, etc.? http://xlsform.org/#metadata

**Comment by cagulas** [comment]
The mockups are below, but please keep in mind the actual field labels and order of the fields should be as per the data dictionary (see Birth Registration tab): https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0

Blank form:
![217469974](https://cloud.githubusercontent.com/assets/3488986/23011952/c7c263ce-f434-11e6-9c05-3625093f0f2d.png)

Partially filled form:
![218849517](https://cloud.githubusercontent.com/assets/3488986/23011960/d6428582-f434-11e6-9258-6ceee0ff9647.png)

Alert for possible duplicate child records:
![217469975](https://cloud.githubusercontent.com/assets/3488986/23011993/f4d6b324-f434-11e6-9d92-0b29d12de1a0.png)

**Note on how possible child duplicate interactions should work in mockup above:**
Possible duplicates list is determined by lookup of required fields `Mother_Guardian_First_Name`, `Last_Name`, `Date_Birth`, and `Sex`

Clicking opens up a list of potential duplicates, where the user can either select someone to say it's a match and cancel the registration (and go to their record), or say it's not any of them and dismiss the alert/warning

This warning and the next would appear as hovering over the form. In that way it is prominent but can still be ignored and potentially dismissed by swiping. Same as a snackbar: https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs

Alert for possible mother match:
![218850429](https://cloud.githubusercontent.com/assets/3488986/23012220/1ebcab84-f436-11e6-93ac-d34f3a2b0cf2.png)

**Note on how possible mother match interaction should work in mockup above:**
This will work the same as the child duplicate interaction above. Possible mother matches list is determined by lookup of required fields `Mother_Guardian_First_Name`, `Mother_Guardian_Last_Name`, and `Mother_Guardian_Date_Birth`. If they select a match, there should be a confirmation window for them to cancel or confirm the mother is a match. If mother is confirmed match, a person relationship between the mother and child should be created in OpenMRS as well as a sibling/sibling relationship to any other children of the mother already in the system.

**Comment by cagulas** [comment]
The child duplicate and mother match interactions are for March, not Feb release.

**Comment by cagulas** [comment]
@maina @jasonrogena @keymane 

I've updated the description to reflect that if the mother's DOB is left blank when the birth registration form is submitted, it should default to 01-01-1960 (for the purposes of creating the patient record in OpenMRS). Also, the mother's DOB and age should only appear in the child detailed view if it was provided in the form. If mother DOB was left blank in the form, on the detailed view, it should be shown as blank as well.

**Comment by cagulas** [comment]
Moved the two remaining features (child duplicate alert and relationship mapping) to two new issues: https://github.com/OpenSRP/opensrp-client/issues/525 and https://github.com/OpenSRP/opensrp-client/issues/526. 

Closing this.
