### ISSUE TITLE
Integrate Facial recognition on Bidan app, Nutritionist and indonesia vaccinator

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client#388]
Integrate Facial recognition for searching data using live picture. and sync the vector data accros health worker

**Comment by baksosapi** [comment]
Finished add Facial Recognition features on Bidan, Gizi and Vaksinator

**Comment by mib-iqbal** [comment]
Re-Open the issue since vaccinator and nutritionist app has not been incorporate yet with facial recognition sync

**Comment by baksosapi** [comment]
done nutritionist and vaccinator
