### ISSUE TITLE
Implement login screen functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#395]
- [x] Add settings menu at the top right which opens settings screen
- [x] Should support multiple users login #394 
- [x] Trim trailing spaces in username/password before login
- [x] Display version no and date built using getVersion() and getBuildDate() methods in the opensrp-app LoginActivity
- [x] Display progress spinner when logging in

![login](https://cloud.githubusercontent.com/assets/360650/22689945/475067dc-ed44-11e6-995d-802050264a3d.png)
**background image to be provided**

**Comment by cagulas** [comment]
![217470623](https://cloud.githubusercontent.com/assets/3488986/23010179/10185b42-f42b-11e6-98fc-c79f42980808.png)


@jasonrogena For the preview release, they have asked for the name to be updated to ZEIR, see above.

**Comment by jasonrogena** [comment]
@cagulas No worries

**Comment by rowo** [comment]
@jasonrogena @maina Background image — do you need the gradient as a png or just the colors?

![opensrp-poweredbylogo](https://cloud.githubusercontent.com/assets/1584163/23139826/6368f03c-f77c-11e6-9ea4-c2801e6e23b6.png)
![zeir-templogo](https://cloud.githubusercontent.com/assets/1584163/23139825/635df4fc-f77c-11e6-8963-197370e9420e.png)

**Comment by jasonrogena** [comment]
@rowo just the colors will do, thanks

**Comment by rowo** [comment]
Background gradient is #449dc1 at the top and #3580a1 at the bottom. Though, I am looking at more neutral colors since we're introducing the boy/girl card colors
