### ISSUE TITLE
Test CouchDB Sync performance

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#397]
Do some testing to ensure scalability of CouchSync.

Two things we need to test.  One is how sync works when there are a lot of records and how sync works when there is a lot of concurrent clients.

**Comment by cagulas** [comment]
@mberg what milestone should this go in?

**Comment by cagulas** [comment]
@maina can we close this issue?

**Comment by pld** [comment]
Have we run tests on this? Can we automate the tests for this?

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#78
