### ISSUE TITLE
Implement home screen functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#398]
- [x] Scan QR code button opens QR code scanner (https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) and on success filters the list using the scanned id. Wrap the code that starts the  scanner "com.google.zxing.client.android.SCAN" intent in a try/catch block to handle ActivityNotFoundException when the QR code scanner app isn't installed. Then in the catch block show an alert dialog asking the user to install QR code scanner app and when they click ok redirect them to google playstore with pname filter as the zxing package:
Uri uri = Uri.parse("market://search?q=pname:" + "com.google.zxing.client.android"); Intent intent = new Intent(Intent.ACTION_VIEW, uri); act.startActivity(intent);
This way we avoid the crash and let the user download the QR code scanner we expect them to install.
- [x] Search - a wild card search in the child register. This is based off of child's name or ID number (`First_Name`, `Last_Name`, `ZEIR_ID` or `Child_Register_Card_Number` from Birth Registration Form)
- [x] Profile image - placeholder image should be in pink for female and blue for male (from `Sex` field in Birth Registration form). Tapping anywhere in first box opens profile detail view screen
- [x] Record weight- opens child card view with weight screen open https://github.com/OpenSRP/opensrp-client/issues/401 
- [x] Due vaccine- should be red for overdue vaccines, blue for due, plain text (date) for upcoming vaccines and not clickable, fully immunized for completed vaccination, inactive for clients marked as inactive (from detailed screen), light blue (upcoming) for vaccines due within the next 7 days. For overdue and due and upcoming (clicking on the column opens immunization screen in child profile view)
- [ ] Sorting the records - The default sort should be by "last interacted with" meaning the last time the profile was modified.

**Note when displaying age:**
From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

![home-view](https://cloud.githubusercontent.com/assets/3488986/22928538/06572160-f2c8-11e6-8387-6dc1abb50d49.png)

**Comment by cagulas** [comment]
Updated home screen below:

![217470550](https://cloud.githubusercontent.com/assets/3488986/23010256/764980d0-f42b-11e6-9c59-8cce106c479d.png)

@maina The name changed to ZEIR, this should reflect on all the screens now. Also, the light blue, upcoming status was removed.

**Comment by maina** [comment]
@keymane  see above

**Comment by keymane** [comment]
cool
