### ISSUE TITLE
Implement actionbar functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#399]
This needs to be done in the base activity so that all the other activities extend the base

![actionbar](https://cloud.githubusercontent.com/assets/360650/22693802/dc037872-ed55-11e6-8494-25a0134a6b19.png)

Here is the choose location widget:

![218832683](https://cloud.githubusercontent.com/assets/3488986/23010404/453322e8-f42c-11e6-9ef3-18314a6bb36e.png)

**Comment by cagulas** [comment]
Related PATH requirements:
- [ ] https://github.com/OpenSRP/opensrp-client/issues/297

**Comment by cagulas** [comment]
One thing I'm noticing is that the red flag icon on top of the bell is still too large. 

From the March 27 build:
![screenshot_20170328-144605](https://cloud.githubusercontent.com/assets/3488986/24403505/dd981440-13c5-11e7-8524-f1856cefcfa1.png)

From mockup:
![2](https://cloud.githubusercontent.com/assets/3488986/24403509/e08f9e5c-13c5-11e7-95e7-2293853fb86a.png)
