### ISSUE TITLE
Implement record weight dialog fragment

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#401]
- [x] The text field for recording weight should have autofocus enabled and only allow numbers (decimals allowed) by enabling Android numeric keypad
- [x] Weight taken today- creates a growth monitoring encounter with the date as the current date, location as the default location set in the app and observations as the weight entered.
- [x] Weight taken earlier- same as weight done today but displays a datepicker to allow the user select a previous date
- [x] Create 'weight' table with columns: _id, base_entity_id,kg(decimal), date,anmid,updated_at(default_timestamp)  to save the weight records

**Note when displaying age:**
From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

![recordweight](https://cloud.githubusercontent.com/assets/360650/22696608/b0512422-ed5f-11e6-8cd0-74a3c4bf3a11.png)

**Comment by cagulas** [comment]
@maina @jasonrogena Think this is self-explanatory, but just in case:

![weight](https://cloud.githubusercontent.com/assets/3488986/23011606/fc5de628-f432-11e6-818b-7f162d9bacc5.png)
