### ISSUE TITLE
Implement overdue and due screen functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#404]
This screen functionality is based on motech alerts from the server side. Due schedules will have alerts with the status 'normal' and overdue ones will have the status as 'urgent'.

- [x] The number overlay on the bell icon at the action bar displays the no of clients with overdue vaccines
- [x] Profile image- placeholder image should be in pink for female and blue for male. Opens profile detail view screen on click
- [x] Record weight- opens weight screen
- [x] Due vaccine- should be red for overdue vaccines, blue for due. (clicking on the column opens immunization screen)

Note when displaying age:
From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

![overdue_due](https://cloud.githubusercontent.com/assets/360650/22727761/aafe8d52-edeb-11e6-942d-d70aa28dcabc.png)

**Comment by cagulas** [comment]
Couple things I'm noticing on the March 27 build:

- The flag is showing total number of due and overdue, it should only show total number of overdue. 
- The top bar should change to what's shown in the screenshot below, i.e replace PB ZEIR with Overdue/Due (total number of kids due - both blue and red reminders)

![217469973](https://cloud.githubusercontent.com/assets/3488986/24402622/165db356-13c2-11e7-9dda-d893fca59056.png)
