### ISSUE TITLE
Implement profile detail view functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#405]
Click on the horizontal view with the profile image in the immunization card to open this view #383 
- [x] Profile details view is a tabbed view (two fragments swapped using a view pager) that lists detailed demographic data in one tab (Registration data) and immunization/weight history (Under five history) in the other. NB: The screen background color changes based on child gender: pink for girls and blue for boys
- [x] The screen has the following menu items
  - [x] Edit Registration data
  - [x] Edit weight data
  - [x] Edit immunization data
  - [x] Mark inactive
  - [x] Mark as lost to follow up
  - [x] Report deceased #424
  - [x] Report adverse event #425
- [x] Clicking on the profile image opens the camera to take photo. Once the photo is taken, it should be compressed(jpeg), renamed to user base_entity_id, stored in the device *internal storage* and a record created in the image repository table ready for upload to the server. See #403 
- [x] In the U5 tab, see all under weights section opens the growth monitoring screen (*TBD*), Edit button against the vaccines allows the user to edit previously given vaccine
-   

**Note when displaying age:**
From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

![details_1](https://cloud.githubusercontent.com/assets/360650/23152952/af5eb6e4-f816-11e6-8f75-7ba4588feaa0.png)

![detailsview](https://cloud.githubusercontent.com/assets/360650/23153244/7e49ab7a-f818-11e6-8a45-4e89b3247e2f.png) 

![details_view_edit_vaccine](https://cloud.githubusercontent.com/assets/360650/23153318/e5d5483a-f818-11e6-8d0b-9383aec23b35.png)

@raihan-mpower @maina New from my trip to Zambia last week:
![vaccine-edit](https://cloud.githubusercontent.com/assets/3488986/24142869/fe6cad4e-0e38-11e7-84ac-fd45ad3bc153.png)
This is the screen you see after selecting "Edit" option next to any of the vaccines. The service date displayed is the original vaccine date. Change service date option changes the date the vaccine was given. The same constraint logic from the vaccine schedules should still apply here. The Undo record vaccination discards the vaccination event completely, i.e., the vaccine was not actually given.

@raihan-mpower here is the edit weight mockup:
![undo-weight](https://cloud.githubusercontent.com/assets/3488986/24198148/a64d0a04-0f15-11e7-8f0d-61a3fbdb0cff.png)
This is the screen you see after selecting "Edit" option next to any of the weights. The service date displayed is the original date weight was recorded. Change service date option changes the date the weight was recorded. Changing the weight decimal is possible as well. This updates the weight that was recorded. Instead of "Delete service", it should actually say "Undo record weight". Tapping this option discards the weight event completely, i.e., the weight was not actually taken.

**Comment by raihan-mpower** [comment]
@james i had a few questions 
what fields change when we click 
 Mark inactive
 Mark as lost to follow up
 Report deceased
 Report adverse event

**Comment by maina** [comment]
@raihan-mpower  Mark inactive, Mark as lost to follow up will be person attributes. For report deceased see #424 and report adverse event see #425

**Comment by raihan-mpower** [comment]
@maina 
- https://github.com/OpenSRP/opensrp-client/blob/path/opensrp-path/src/main/java/org/ei/opensrp/path/domain/VaccineWrapper.java 
has the lines 
 public void setUpdatedVaccineDate(DateTime updatedVaccineDate, boolean today) {
        this.today = today;
        this.updatedVaccineDate = updatedVaccineDate;
        if (!isToday()) {
            this.recordedDate = new DateTime(new Date());
        } else {
            this.recordedDate = updatedVaccineDate;
        }
    }
so even when I am giving a previous date the vaccination date is getting recorded as today's date

- for report deceased and report adverse do i launch the forms #424 and #425 . Are they available yet ? I am writing a dummy launch form method for the time being.
- mark inactive and mark as lost to follow up would be update in attributes , i am confused regarding this
-the weight is suppose to keep multiple records but right now according to https://github.com/OpenSRP/opensrp-client/blob/path/opensrp-app/src/main/java/org/ei/opensrp/repository/WeightRepository.java we have 
    if (weight.getId() == null) {
            weight.setId(database.insert(WEIGHT_TABLE_NAME, null, createValuesFor(weight)));
        } else {
            String idSelection = ID_COLUMN + " = ?";
            database.update(WEIGHT_TABLE_NAME, createValuesFor(weight), idSelection, new String[]{weight.getId().toString()});
        }
so if weight was recorded before it is only getting updated and not a new service date is being added
Hence I am getting only one weight row even after myltiple recording in different dates 

-  Edit weight : if i delete service which one do I delete in case of weight, the most previous one?
-edit data : i think i need a call regarding this as i tried to update documents and the event to update details is still clouded for me

**Comment by cagulas** [comment]
@raihan-mpower Just a quick note on the detailed page mockup above. Everywhere it should say "immunisations" with an "s" instead of "immunizations" with a "z". Also, the "kg" is missing next to the first weight (8.4). This is a typo. The "kg" should appear next to all weights.

**Comment by cagulas** [comment]
@raihan-mpower @maina I have added the following two attributes to the Ona OMRS instance:
- Inactive (boolean)
- Lost_to_Follow_Up (boolean)

**Comment by raihan-mpower** [comment]
@cagulas  what does the catchment area stand for and which variable is it referencing

**Comment by cagulas** [comment]
@raihan-mpower These fields are coming directly from the Birth Registration Form. If you follow [this link](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0), tab over to the Birth Registration tab. This lists the fields from the Birth Registration form (and their variable names in column B). So the "Registration Data" view in the mockup above is just displaying the fields from the Birth Registration form. The mockup should be used for the overall UI and font, etc, but the field labels and variable names should follow what you find here in the spreadsheet and the order of the fields should follow what you see in this spreadsheet as well. Let me know if anything's still not clear.

**Comment by cagulas** [comment]
![icon-losttofollowup](https://cloud.githubusercontent.com/assets/1584163/24261346/0ede0c96-0fcd-11e7-8f08-c8e1f74c62c5.png)

Lost to follow up icon above.

**Comment by cagulas** [comment]
@raihan-mpower 

The detailed view looks good, but there is some clean up I think we can do. See below. Also, the top action bar should be fixed. Currently, when you're on the Registration Data tab, if you scroll down, the top action bar scrolls out of view. It should remained fixed in place.

![detail-view](https://cloud.githubusercontent.com/assets/3488986/24499389/3178593c-154a-11e7-88b4-ace6f131e526.png)

**Comment by cagulas** [comment]
![history](https://cloud.githubusercontent.com/assets/3488986/24500268/5b2c244a-154d-11e7-957a-082f207d2d1a.png)

**Comment by cagulas** [comment]
![edit-weight](https://cloud.githubusercontent.com/assets/3488986/24501174/0f0c3736-1551-11e7-82a7-1f6bf92e4d5b.png)

**Comment by cagulas** [comment]
![edit-vaccine](https://cloud.githubusercontent.com/assets/3488986/24501676/388d7e2e-1553-11e7-8fd5-3b9c66aab7e6.png)

**Comment by raihan-mpower** [comment]
@maina Residential_Area , Residential_Area_Other , Residential_Address are giving me no values although they have been recorded in the form

**Comment by raihan-mpower** [comment]
@cagulas fixed most of them apart from the one issue mentioned above , scroll (the vaccine screen does scroll in my end , can you recheck) and mark as inactive and mark as lost to followup (these two i am working on right now)
