### ISSUE TITLE
Implement advanced search screen functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#407]
- [x] By default the search limit should be set to "Outside and Inside My Catchment Area". This should first check device connectivity status whereby the option should only work if the device is connected to the internet.
- [x] This screen does the actual search and if matching records are found, view search results screen is displayed. This could be done by passing baseentityids of clients found to the view search results screen #423

![217469965](https://cloud.githubusercontent.com/assets/3488986/24284617/2e6f1a54-107d-11e7-94b1-72e5a7304db6.png)

Displaying results: #423

![218856973](https://cloud.githubusercontent.com/assets/3488986/24284634/45f7bff0-107d-11e7-816c-eed97740d1ff.png)

The "Record service" button opens the out of catchment area service form and inserts the child's ZEIR ID automatically into the form. The "Move to my catchment" button syncs the record to the device (requires internet connection) and changes the child's Home_Facility to that clinic.

**Comment by cagulas** [comment]
@maina @keymane I updated the screen shots in this issue from invision. I think the issue was created before they were finalized. 

I think this is obvious, but active, inactive, and lost to follow-up refer to the statuses from the detailed profile view.
