### ISSUE TITLE
Implement functionality to record out of area vaccination/weight

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#408]
Out of area is a workflow for vaccinating or recording weight for kids who are from another clinic without necessarily having to sync their data to the clinic they visit if their unique identifier is known. This view records child's id, vaccine offered and date given.  A child vaccination or growth monitoring encounter is then created with the default location as set in the device, vaccine(s) given  or weight recorded (growth monitoring event) as obs and identifiers as ZEIR id. Once the encounter syncs to the server, the server does a clients lookup in the db using zeir id and sets the encounter baseEntityId value.(https://github.com/OpenSRP/opensrp-server/issues/207)

![out-of-area](https://cloud.githubusercontent.com/assets/360650/23693551/f4b81bf6-03e5-11e7-9936-289283b62762.png)

**Comment by cagulas** [comment]
https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1173845481

Please see the `Out of Area Service` tab for the form field definitions.
