### ISSUE TITLE
Implement app menu sidebar

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#412]
![217767414](https://cloud.githubusercontent.com/assets/3488986/23010470/a6e4cfc8-f42c-11e6-9bf2-ba719086fffa.png)

@maina I realized this was a missing issue. Can this be partially in place for the preview release, i.e., the log out button should be there ideally as well as the user initials.

- [x] You get to this menu bar by tapping the user initials in the top left of the home screen, in this case "RW"
- [x] You can close this menu by tapping anywhere outside the menu bar (or the "X" in the top right)
- [x] User initials and name pulled from OpenMRS team mgmt module
- [x] Log out returns you to the login screen
- [x] Register button launches the birth registration form
- [ ] Record out of catchment launches the out of catchment service form https://github.com/OpenSRP/opensrp-client/issues/408
- [x] Settings - do we need this? There won't be a change language option, so not sure this is needed, unless this goes to a provider details page, like we see in PK app. @rowo thoughts?
- [x] Tapping sync button triggers a server sync. This should also happen automatically, but an extra sync can be triggered when this is tapped. Shows the time of the last sync

**Comment by rowo** [comment]
@cagulas we can get rid of settings if there's nothing in there. I can imagine more stuff going in there after March, for example sync settings or that provider detail page.

**Comment by cagulas** [comment]
Ok, great, let's drop it for now then.

**Comment by jasonrogena** [comment]
@cagulas @rowo It might not be possible to do the sync button the way it is in the mockups. Having secondary text in the button was added in a later version of the library. Updating the library might mean other views will break

**Comment by cagulas** [comment]
@rowo I discussed with @jasonrogena and he just means it can't be secondary text, but we can include last synced info in the same line and same font as the "Sync" text itself and put in brackets for example.

**Comment by rowo** [comment]
@cagulas Oh ok. We'll have to edit it a bit then. Looking at it now, I think the "up to date" part is unnecessary and maybe incorrect. The app would not know if it is completely up to date since it wouldn't be able to tell what's on the server without a sync. So we could just show last synced and if there are any forms that are unsynced on the device like so: 

**App has records that are unsynced (services done that haven't been sent up)**
"Sync (last 2d – 4 records unsynced)

**App has nothing to sync**
"Sync (last 3h)"

What do y'all think?

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
@maina @jasonrogena Did you see the above discussion about not needing Settings option? It's currently there in the app, which takes you to the base url settings page, but is this needed? I don't think you can change the base url settings once you're already logged in, right?
