### ISSUE TITLE
Implement record weight reminder

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#414]
![218192534](https://cloud.githubusercontent.com/assets/3488986/23012644/494a206e-f438-11e6-8fa2-07073d13e768.png)

**Comment by cagulas** [comment]
Of interest: https://github.com/Tapadoo/Alerter

**Comment by cagulas** [comment]
This reminder appears if the nurse marks a vaccine on the page before weight. From the visit, weights are always recorded first, so if a vaccine is recorded first, this reminder should appear, as it's likely the nurse forgot to enter the weight data.

**Comment by jasonrogena** [comment]
Reminder revised to this ![record_weight_reminder](https://cloud.githubusercontent.com/assets/2384176/24741879/75d19b6e-1ab0-11e7-9f73-eacb78910c1e.png)
