### ISSUE TITLE
Feedback from PATH and Ona on ZEIR preview release

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#420]
- [x] Make sure the Zones are listed in order in all location drop-downs (1, 2, 3, etc.)
- [x] Some of the age cutoffs are incorrect, e.g., 3w 7d should be 4w
- Something needs to be done to show the weight was given, so maybe show the weight (kg) that was just recorded for a period of 24hrs, or show an undo option. RW: see below https://github.com/OpenSRP/opensrp-client/issues/420#issuecomment-284077281
- Look into showing an icon for health facility vs. zone in the service location drop-down ( @rowo ) RW: an icon isn't necessary, just design to [original specs](https://projects.invisionapp.com/d/main#/console/10214563/218832683/preview) with a checkmark or nothing
- [x] The red overdue reminder in the vaccine card view is different color from the red reminder on the home screen; it should be same as the home screen red color
  RW: verified: <img src="https://cloud.githubusercontent.com/assets/1584163/23677906/ef049c34-034f-11e7-838b-e24d12844a3d.png" width="280">
- [x] The question labels in the birth registration form should be 1-2 pixels larger
- [x] Make the text of the vaccines in the vaccine modals tappable in addition to the checkbox
- [ ] How are you creating the initials for the logged in user? For example, biddemo is showing as "PB", but in OMRS, the given name is "PATH BID Zambia" and the family name is "Demo User", so the initials should be the first letter of given name and first letter of last name, so "PD"
- [x] The constraints in the Birth Registration form are not added. Please see the data dictionary [here](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0). I've highlighted the data constraints that need to be added in column J in yellow. 
- [x] home
  <img src="https://cloud.githubusercontent.com/assets/3488986/23542542/df0c72e2-fffe-11e6-9bd5-8cb85b454582.png" width="480">

- [x] card
  <img src="https://cloud.githubusercontent.com/assets/3488986/23542857/73d82dac-0000-11e7-80c6-d43da45702de.png" width="480">
  RW: I think we can leave the arrow as is. What's shown above was the previous Android standard that they've since updated to this back arrow icon. I don't see a reason to deviate from standard since other apps people might be using on the device will use the same icon.

- [x] weight
  <img src="https://cloud.githubusercontent.com/assets/3488986/23543026/4b602a2c-0001-11e7-9583-9e29ce0163f2.png" width="480">

- [x] multiple
  <img src="https://cloud.githubusercontent.com/assets/3488986/23543483/74c4f526-0003-11e7-8a97-a930148ea1f8.png" width="480">

- [x] registration
  <img src="https://cloud.githubusercontent.com/assets/3488986/23544055/4fff84a6-0006-11e7-82be-b468959cd189.png" width="480">

- [x] registration
  <img src="https://cloud.githubusercontent.com/assets/3488986/23544229/2f259ad0-0007-11e7-8cad-0bbe321cdff2.png" width="480">

- [x] registration
  <img src="https://cloud.githubusercontent.com/assets/3488986/23544394/da9e8ba6-0007-11e7-8c0d-324d42794b5f.png" width="480">

- [x] registration
  <img src="https://cloud.githubusercontent.com/assets/3488986/23544739/3361c400-0009-11e7-9561-6be5495da38a.png" width="480">

**Comment by rowo** [comment]
Record Weight button label change. 

To be determined:
- How long does it keep this state?
- Is it still clickable? If so, is it about editing? 
- If it's no longer clickable, maybe it should be a non-button (i.e. white background)

![20170303-vaccine-app-card-record-weight](https://cloud.githubusercontent.com/assets/1584163/23569872/98d96c0e-002f-11e7-9c3d-69ebdfd8678a.png)
![20170303-vaccine-app-home-record-weight](https://cloud.githubusercontent.com/assets/1584163/23569873/98db2d1e-002f-11e7-9b08-1799224bcd80.png)

**Comment by rowo** [comment]
Few things I noticed:

<img src="https://cloud.githubusercontent.com/assets/1584163/23675969/107e0d48-0349-11e7-87d1-c0dd81c6c0a8.png" width="400">

<img src="https://cloud.githubusercontent.com/assets/1584163/23675968/107d6cf8-0349-11e7-8f8b-bbc72b4032b2.png" width="400">

<img src="https://cloud.githubusercontent.com/assets/1584163/23675970/107f423a-0349-11e7-9a42-e2e64cece86c.png" width="400">

**Comment by maina** [comment]
@cagulas for this "How are you creating the initials for the logged in user? For example, biddemo is showing as "PB", but in OMRS, the given name is "PATH BID Zambia" and the family name is "Demo User", so the initials should be the first letter of given name and first letter of last name, so "PD"", it's not possible to come up with "PD" from the names given. The person object we get from OpenMRS has the name as full name "PATH BID Zambia Demo User" which is difficult to tell which name is first/last name.

**Comment by cagulas** [comment]
@maina ok, thanks for explaining. I guess this won't be an issue with real users, because they'll likely only enter two names. Ok, noted.

**Comment by cagulas** [comment]
Make sure the weight button changes to a non-tappable white button showing the weight in kg after weight is recorded. Right now, it is showing as a grey button, and you can also tap it again to edit the weight.

**Comment by cagulas** [comment]
Everything is fixed or captured in the https://github.com/OpenSRP/opensrp-client/issues/446 issue, so closing this.
