### ISSUE TITLE
Implement report adverse event functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#425]
This is a native form for reporting adverse event 
Ref Zambia-EIR-DataDictionaryPrimary, "Report Adverse Event" tab

https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=875643195

**Comment by cagulas** [comment]
We actually decided this could be an enketo form. Simply because it will rarely be filled out. @maina I am happy to make an enketo form, but if there's no difference in level of effort, I guess it could be a native form.

**Comment by maina** [comment]
@cagulas that's fine, go ahead and create an enketo form

**Comment by cagulas** [comment]
Update from my trip to LVI last week: There are no concepts for many of the fields in the AEFI form, so at this point, it would just be an Enketo form in the app, and it wouldn't be able to go into OpenMRS at this point. @paulnindi and PATH team are discussing a few options we came up with during the visit last week and they will let us know.

**Comment by cagulas** [comment]
Report Adverse Event form is signed off, so it can now be worked on. Have updated the original issue above with the relevant info.
