### ISSUE TITLE
Feedback from BID - 28th February preview release 

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#427]
- [x] Password not masked on the login screen. this should be masked to either ****** or ........

- [x] Filling in a Registration form encountered the following error “cannot create register form no ids allocated kindly contact system admin.” The error came twice but the rest of the attempts form worked just fine. work to ensure enough ids are assigned to the device. at-least 200 IDS assigned to a device for offline functionality.

- [x] adding field validations to Name fields for Child, mother, father and CHW. system accepting numbers and special characters.

- [x] searching by ZEIR ID partially working. Sometimes gives results and on some attempts does not give results. Also sometimes gives results that are out of range.

- [x] changing of service location should be possible. Once you click on Linda (service location) to change the service location to one of the outreach zones under Linda you cannot change back to the default service location (Linda) unless login out.

- [x] Real time validation of fields.  validation for text fields, NRC and phone number happens only after clicking the save button. Validation to happen when user navigates away from the field 

- [x] Mandatory fields check Should highlight all the fields that need filling to avoid user clicking the save button back and forth. Apparently Only highlights one field at a time and focus (cursor) is returned to that field.

- [x] system Accepting Date first seen (DFS) to be earlier than DOB. DFS should not be earlier than DOB

- [x] Crushing on occasions with the following error ''unfortunately ZEIR has stopped working. one has to login again.

- [x] Due date display only shows day and month i.e 01/03 and year is missing. year can  be included as well

- [x]  following screen appearing (still investigating on how to reduce screen) came forth twice. )

![screenshot_2017-03-09-06-27-45](https://cloud.githubusercontent.com/assets/25152366/23783604/6f2ea028-0565-11e7-8d85-877e8f3dfeae.png)

- [x] Ordering of the home names should be as to last date modified. last record to be modified tops the list.

**Comment by cagulas** [comment]
Closing this issue, everything is done or covered in https://github.com/OpenSRP/opensrp-client/issues/446
