### ISSUE TITLE
Feedback from the clinics - (Ona/BID/BlueCode visit) - 28 February Release

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#429]
- [ ] BCG labelling on the side menu should be rephrased as ''Record BCG 2 (if no scar)''. This feedback was from the BCG 2nd dose Mockups. CG: see https://github.com/OpenSRP/opensrp-client/issues/426

- [ ] Of the two options for undoing a vaccine (grey undo button vs. red delete button), they preferred the grey undo buttons. The red delete button gave the impression of deleting the entire child record, whereas undo sounds safer to them. CG: see https://github.com/OpenSRP/opensrp-client/issues/405

- [x] Registration - Child's DOB - they thought it was the father's DOB, since it was directly below the father fields in the birth registration form. The registration form should be re-odered as to the registration mockup  - https://projects.invisionapp.com/d/main#/console/10214563/218849517/build CG: I have re-ordered the fields in the [data dictionary](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0) to match this. I have highlighted the re-arranged rows in light green (ID column only).

- [x] Weight: on recording weight., nurses preferred having to type the decimal point  as opposed to having a preset decimal point in the system. They felt they would get confused say if weight is only 7.. then you have to type 70 and if you just type 7 then it will appear  as 0.7

- [x] Father name field should read Enter Father/guardian full name. since the first name and last name is required here. CG: I have updated the data dictionary here as well. See yellow highlighted cell in row 19.

- [x] Slightly increase font size and or contrast for the fields as some nurses were observed to struggle with reading the fields names. CG: This is referring to all native forms.

- [x] Show the date when vaccine was given on the vaccine card.- right now it just shows the green check.

- [ ] Add an ellipsis (...) to mother/guardian name to ensure it doesn't bleed into the child's age.

- [x] Look at alternatives for date picker. The ones where you see the date, month, year, might be easier for the nurses to pick up. As it was, the nurses didn't know how to go back to previous years, and the date picker itself has a very small font size that is hard to see for some nurses.

**Comment by cagulas** [comment]
Closing this issue. Everything is done or covered in the https://github.com/OpenSRP/opensrp-client/issues/446 issue.
