### ISSUE TITLE
Edit EC Form

### ISSUE THREAD

**Issue by howru42** [OpenSRP/opensrp-client#43]
ANM Password is not working to edit ec Form. Can any one suggest me

**Comment by ndisha** [comment]
@howru42 please expound on what you mean for us to be able to assist you (if you have not figured out the problem yet). Which ANM username and password are you using? Do you have the latest opensrp client app?

**Comment by raihan-mpower** [comment]
1 as password

**Comment by howru42** [comment]
i tried this, but it is not working....

**Comment by cagulas** [comment]
Try c as the password.  Alternatively, if you give me your Ona username, all of the Dristhi xlsforms are uploaded to the OpenSRP org on Ona, which you can check out and download.

**Comment by howru42** [comment]
ya... thanks C is the password
