### ISSUE TITLE
FormSubmission Sync huge size issue

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client#430]
If form submissions are not synced for a long time app stops syncing and device runs out of memory when loading unsynced form submissions. This should be addressed by limiting number of rows loaded for sending to server.

**Comment by mib-iqbal** [comment]
we found the same problem on our app, @MarwanNulhakam has already solved that by limiting the cursor length to sync by 100 form-submission. @MarwanNulhakam can you help regarding this.

**Comment by maimoonak** [comment]
Thanks Iqbal. We already have fixed it. Was thinking to merge it in master. But I guess your work should already be in master!

**Comment by MarwanNulhakam** [comment]
it caused by cursor length that can't be handled when sync to server. in my case, I limit the cursor length to only 100 per sync.

you may check on FormSubmissionSyncService at method pushToServer(). 
`public void pushToServer() {
        List<FormSubmission> pendingFormSubmissions = formDataRepository.getPendingFormSubmissions();
        if (pendingFormSubmissions.isEmpty()) {
            return;
        }
        if(pendingFormSubmissions.size()>100) {
            pendingFormSubmissions = formDataRepository.getPendingFormSubmissions().subList(1, 100);
        }
        String jsonPayload = mapToFormSubmissionDTO(pendingFormSubmissions);
        Response<String> response = httpAgent.post(
                format("{0}/{1}",
                        configuration.dristhiBaseURL(),
                        FORM_SUBMISSIONS_PATH),
                jsonPayload);
        if (response.isFailure()) {
            logError(format("Form submissions sync failed. Submissions:  {0}", pendingFormSubmissions));
            return;
        }
        formDataRepository.markFormSubmissionsAsSynced(pendingFormSubmissions);
        logInfo(format("Form submissions sync successfully. Submissions:  {0}", pendingFormSubmissions));
    }`

**Comment by mib-iqbal** [comment]
oh okay please merge this, we haven't merge our code yet to master since our focus right now is in EC app (v2).
