### ISSUE TITLE
Create a native form on the tablet to fill out the entire HIA2 report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#438]
The fields related to child health that can be aggregated automatically from ZEIR will be populated into the form. The nurse will be allowed to edit these values, and they will also fill in the rest of the values for the remaining report (i.e., the fields that cannot be captured through ZEIR). After submission, the data will feed directly from OpenSRP server into Ona and Zambia DHIS2 instances (https://github.com/OpenSRP/opensrp-server/issues/211).

**Comment by cagulas** [comment]
@tobiasmakai We have the fields for HIA2 Child Health, but where can we get the remaining fields from the HIA2 report (i.e., for the other sections, like reproductive health, disease, etc)? Can BlueCode add the remaining fields from HIA2 report in the reporting data dictionary, maybe in a new tab? For this, I think we need to know the variable name, label, and data type only.

**Comment by tobiasmakai** [comment]
This looks okay, we are going to fill up the HIA2-OtherSections

**Comment by cagulas** [comment]
Replaced with implementation issue https://github.com/OpenSRP/opensrp-client/issues/520
