### ISSUE TITLE
Create the child health HIA2 report view for Android devices

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#439]
Using the local tablet database, create a HIA2 report with data outlined in the Reporting Data Dictionary below:
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=2010018538

The android report view will only feature child health information.
The report should support online and offline modes of interaction.
It should be updated regularly during the month.

**Comment by geoffreymuchai** [comment]
Here is additional information for the data format of the form when exporting out to DHIS2

```
   {
   "dataValues":[
      {
         "dataElement":"WFxN7txijYV",
         "period":"201401",
         "orgUnit":"qGmkMMWDHOm",
         "value":"12"
      },
      {
         "dataElement":"EtOcAIMlPG9",
         "period":"201401",
         "orgUnit":"PijOYGG1b54",
         "value":"14"
      }
   ]
}
```

The data elements DHIS2 IDs are in the attached file:

[HIA2Elements.xlsx](https://github.com/OpenSRP/opensrp-client/files/878690/HIA2Elements.xlsx)

**Comment by cagulas** [comment]
Closing this issue. I think this is replaced with the implementation mockup issues.
