### ISSUE TITLE
Add the ability to print the HIA2 report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#440]
The report can be exported into a printable format e.g. pdf that can be later printed on paper for review.

**Comment by cagulas** [comment]
Waiting on clarifications from PATH team on this intended functionality.

**Comment by cagulas** [comment]
From the last call with the team, this feature would be available on the online dashboard only. This is because this will likely only be done by the folks at the district office, since the health facilities most likely won't have a printer available at the facility.

**Comment by cagulas** [comment]
This feature is redundant, since printing facility is available in DHIS2 when viewing monthly report.
