### ISSUE TITLE
Research the DHIS2 Dashboard Android app to determine if we can use it for the tablet reporting requirements

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#441]
The key aspects to investigate are:
- [x] What kind of functionality does it support for reports?
- [x] Does it have the ability to print reports?
- [x] Does it support automatic updating of reports when data changes on DHIS2?
- [x] Does it support offline report views?
- [x] What kind of authentication does it support?

**Comment by tobiasmakai** [comment]
Shall be looked into

**Comment by geoffreymuchai** [comment]
*Research Notes*
- The apk from the android store has a bug that prevents a user from logging into the system

**Comment by geoffreymuchai** [comment]
*What kind of functionality does it support for reports?*
- User authentication based on DHIS2 user accounts
- Synchronization of dashboard charts with live DHIS2 instance.
- No ability to sync updates to dashboards without logging out
- No ability for custom filters on the android application based on user's permissions and assigned locations

*Does it have the ability to print reports?*
- No

*Does it support automatic updating of reports when data changes on DHIS2?*
- No

*Does it support offline report views?*
- It only displays data that had been synced before the device went offline

*What kind of authentication does it support?*
- DHIS2 user authentication using DHIS2 user accounts. The user has to specify the DHIS2 online url while logging in. Failure to provide the http protocol text i.e. http or https results in a failure in authentication and no error message is displayed

**Comment by cagulas** [comment]
@geoffreymuchai Sorry if you explained this on the call, but what do you mean by "No ability to sync updates to dashboards without logging out"?

Does this mean in order to "refresh" the dashboards to get the latest data, you have to log out and log back in? Is the data wiped each time you log out?

Have you found anywhere a product development roadmap for the app? If it exists, it would be helpful to see if any of the functionalities we would need are under development or planned.

**Comment by tobiasmakai** [comment]
Our findings were similar to @geoffreymuchai's
**What kind of functionality does it support for reports?**
-clear and easy to view display of indicators i.e charts, graphs, maps for literally all reports of  interest to ZEIR. The display is particularly nice.
-easy manage but no support for high level configuration of dashboard one has to go back to the web instance
-not  a stand alone apk highly dependent on the web dhis2 instance and logging in demands the web url for the particular dhis2 instance
**Does it have the ability to print reports?**
-No
**Does it support automatic updating of reports when data changes on DHIS2?**
-No - for any updates to occur user has to refresh by logging out and back in. This is not good for maintaining reliable and up to date reports.
**Does it support offline report views?**
-No- displays the views that were there before the user went offline but when the device is turned off and on or when it stays on standby for a long time the report views wont show (only the dhis2 logo as a placeholder gets show).
**What kind of authentication does it support?**
User has to use their web dhis2 instance account information and they have  to enter a full url of the web based dhis2 instance. Having to enter the lengthy url when logging in can be a bit complicated for lay users.
**General Impression**
-At the moment the dhis2 android apk is not suitable for ZEIR reporting requirements unless after further testing and exploration. Having to bring in the use of yet another apk in addition to ZEIR for reports will not be so ideal for the user.
