### ISSUE TITLE
Add the Cohort Coverage Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#447]
**Description**
Vaccination coverage as the percentage of the children living in a certain area, that were born in a certain timeframe, and that were vaccinated with a certain vaccine dose (cohort reporting).

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#76
