### ISSUE TITLE
Create Vaccine wastage DHIS2 Dashboard report

### ISSUE THREAD

**Issue by tobiasmakai** [OpenSRP/opensrp-client#453]
**Description**
A monthly visual display of the number of vaccine doses that are issued to a health facility but are not administered to the children.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for calculated stock wastage indicators in DHIS2
2. Define parameters
3. Create DHIS2 Chart for trend analysis
4. Place chart into DHIS2 Dashboard

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#59
