### ISSUE TITLE
Create Penta dropout rate DHIS2 Dashboard report

### ISSUE THREAD

**Issue by tobiasmakai** [OpenSRP/opensrp-client#456]
**Description**
Month to month visual comparison between number of children who start the immunization schedule against the number who complete it.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick elements for calculated Penta1 to Penta3 dropout rate in DHIS2.
2. Define required parameters
3. Create DHIS2 charts
4. Place chart into DHIS2 Dashboards

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#56
