### ISSUE TITLE
create location hierarchy for the demotest user in correspondence to the drishti forms

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#46]
{"district":"mysore",
"phcName":"Bherya",
"phcIdentifier":"bherya",
"subCenter":"munjanahalli",
"villages":["chikkabherya","kavalu_hosur","munjanahalli"]}

can we have the above structure location map for the demotest user.......since the people who would download the opensrp client  would use drishti forms and this is the location the drishti form uses.......so if the user demotest can be mapped to a similar structure we can add to the modal ui for the client.

@maimoonak can you look into this and give me a feedback

**Comment by maimoonak** [comment]
@raihan-mpower this location mapping  was maintained in postgres in location table that was very tightly coupled to Indian system. To get rid of this structure we adapted OpenMRS location which is flexible and mappable to any system. Also we had discussed that no one should use old way of mapping locations i.e. drishti forms way. 
OpenMRS location management is pretty dynamic and it may not be wise to restrict it to follow this type of scheme.

**Comment by raihan-mpower** [comment]
what i meant was using similar named structure for locations in the demotest user's location so that we can use it for the ec_registration forms........

**Comment by maimoonak** [comment]
unfortunately, this is going to make things complex and messy at the backend. If someone wants to use old form with new app they should change their location mappings as per our new scheme because neither we are authenticating nor we are managing locations in drishti.
