### ISSUE TITLE
Create Total not gaining weight < 5 years DHIS2 Dashboard report

### ISSUE THREAD

**Issue by tobiasmakai** [OpenSRP/opensrp-client#465]
**Description**
Month to month visual of the number of total children < five years who were weighed for 2 consecutive months who did not gain >100g of weight in those months.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for calculated total number of children under 5 not gaining weight from DHIS2.
2. Define chart parameters
3. Create chart
4. Place chart into  Immunization DHIS2 Dashboards

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#47
