### ISSUE TITLE
31st march release Initial Feedback

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#470]
- [ ] Login : Logging in the system for the first time took several attempts (4 times) before logging in even with the internet on and the right credentials. Gave an impression that the credentials were wrong.
CG: I have not experienced this with this release (March 31 release). It might be because everyone is using the same login, but we'll look into this.

- [ ] Vaccine - Vaccine schedule Not working efficiently. A child can be registered, and doesn't show any vaccines due with the vaccine due button on the home page grayed out (white). Even when going to the vaccine card details the vaccine fields are grayed out and when you check the vaccine history, it would show some vaccines were given out with dates showing. see scree short for a 4 weeks baby. 
CG: This was already flagged and is being added in the https://github.com/OpenSRP/opensrp-client/issues/446 issue.

- [ ] Vaccines:  Due Vaccine Button- Suggestion to add a tick for vaccines given on the home button. An alternative will be to change the label name of the vaccines button when vaccines have been given to a tick followed by the vaccines due e.g Birth Vaccines recorded. 6 wks vaccines recorded. If this is crowding the button, the first option will be a nice to have.  Currently it would seem they are also due. 
CG: This was discussed on the call yesterday, and Roger provided a solution in the https://github.com/OpenSRP/opensrp-client/issues/446 comment area.

- [ ] Vaccines: Recording one vaccines out of a number due deactivates the overdue or due status. If two vaccines were due and one was not given, the status should remain due or over due.  should not change because sometimes clinics may not have some vaccines on that day.
CG: @paulnindi I don't see this happening. For instance. Child Banda (ID: 1059500) was due for OPV 0 and BCG. I only gave OPV 0. On the home screen, it still shows birth vaccines due.
CG: Update, I have been able to observe this with child Mary Mwelwa (ID: 1038504). I gave all 6 weeks vaccines, except for Rota 1. On the home screen, it showed due 10 weeks when it should still show due 6 weeks since Rota 1 was not given. @maina can hopefully look into this.

- [ ] System: crushing: Had one crush but hasn't occurred again. something to be on the look out for (observing) 

- [ ]  Vaccination - Default vaccination location. vaccination facility e.g (Linda) needs to be the default selection. For some reason had zone 3 selected. 
CG: I think Linda is the default location. It probably showed Zone 3, because multiple people are sharing the same login and someone had selected Zone 3.

- [ ] Registration: Date Format - Date format on registration picker needs to change to ddmmyyy. This is a very easy date picker. Good to have this one. 
CG: Ok, @jasonrogena can look into this. Jason, can the format be changed to DD MMM YYYY? Think it's still good to show the month in letters not numbers, so let's try to keep that.

- [ ] Registration-Suggestion to have a warning when cancelling the registration. Accidentally clicking on the system back button clears off the screen with no warning. A back button on top can also be a nice to have and can be used to cancel the registration too.
CG: Already flagged and will be added in https://github.com/OpenSRP/opensrp-client/issues/446 issue.

- [ ] Registration- Zones in the registration form are still not in order. appearing as 1, 3, 4, 2, 5
CG: Already fixed in https://github.com/OpenSRP/opensrp-client/issues/446 issue.

- [ ] -Vaccination: Outside catchment area -  When clicked a a white form comes in landscape with a label ''enter User name'' and next button which is inactive. when you click the system back button, that is when the outside catchment form is loaded.  Clicking on the ZEIR ID launches the same white form which i think should be the scanner. 
CG: @paulnindi can you provide a screenshot of this? I have not seen this. Did the tablet you were using have the QR code scanner app installed on it?

**Comment by cagulas** [comment]
I have incorporated the remaining issues from this into https://github.com/OpenSRP/opensrp-client/issues/475. Closing this issue.
