### ISSUE TITLE
Integrating Device interface (Bluetooth blood pressure monitor) into Bidan Opensrp 

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client#472]
Integrating Bluetooth blood pressure monitoring app  into Bidan opensrp

**Comment by sohelsarder** [comment]
Are you buying any new devices for it?

**Comment by mib-iqbal** [comment]
yes, we are buying new BP device with Bluetooth for this

**Comment by sohelsarder** [comment]
Would it possible to share technical specification for that device and price of it? What use case involve with this device usages?

**Comment by baksosapi** [comment]
We use type BP7 and using https://github.com/iHealthLabs/Android-SDK

**Comment by baksosapi** [comment]
Done [c6e1ce5](https://github.com/OpenSRP/opensrp-client/commit/c6e1ce5a9893705d9cb801735e2c5319bdb946e9)
