### ISSUE TITLE
Add new UI elements to ZEIR app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#474]
- [x] On home screen, add check mark to vaccines recently recorded a la weight recently recorded (see Joyce Mwanza):
<img src="https://cloud.githubusercontent.com/assets/3488986/24787605/08bbc6c2-1b72-11e7-9655-720df181b5a7.png" width="400px">

CG: This can be the status immediately shown when vaccines are recorded, and then it can be updated to the next vaccine due date status when it syncs with the scheduling engine. Please note, however, that if not all the vaccines are given (e.g., only BCG is given, but OPV 0 was not), the status should remain the same due status for the birth vaccines. In future, we can see about changing the status to only show which vaccine was not given, but for now, I think it's ok to just continue to show due at birth.

- [x] Change how status is changed by moving choices to a simple menu:
<img src="https://cloud.githubusercontent.com/assets/3488986/24787449/093ba3a2-1b71-11e7-840a-3f43c0f68cd6.png" width="400px">

- [x] When you click on "Change status" above, it opens a modal similar to the service location dropdown:
<img src="https://cloud.githubusercontent.com/assets/3488986/24787505/467f2d60-1b71-11e7-8373-5e0ee6307c4a.png"  width="400px">

Important notes: You should also be able to get to the child status modal (above) by clicking on the child's current displayed status in the detailed view (the icon next to their name and image).  Clicking outside of the menu closes it without changes. Clicking the same option closes the menu without changes. Clicking on another option updates the status and closes the window.

- [x] Add new icon to vaccine card to signify you can tap here to open the detailed view:
<img src="https://cloud.githubusercontent.com/assets/3488986/24787805/0442d51c-1b73-11e7-8e60-2d83b7e0adba.png"  width="400px">

Icon: https://material.io/icons/#ic_more_vert

After sync is clicked, we need some sort of indication that (1) the sync button was clicked and (2) it is currently syncing. A snackbar at the bottom would be nice. So after you click "Sync" in the menu:
- [x] The menu closes (like it does now) and a snackbar shows up:
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812096/c55bd3ca-1b96-11e7-9be8-49a25cb512b4.png" width="300">
- [x] Additionally, we could replace the initials avatar with an animated sync icon:
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812448/20020884-1b98-11e7-8a1a-4b53ac2555c9.png" width="200">
- [x] When the sync is complete, this shows up: 
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812120/dd5db696-1b96-11e7-9414-2e38186a8bdc.png" width="300"> 
- [ ] If there's an error, this shows up (and disappears if click happens anywhere else):
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812238/410eee76-1b97-11e7-8be1-07074a84dc90.png" width="300">
-  [x] If the user opens the menu up while syncing is happening, what appears is the label should change to "Syncing...". It would be nice if the sync icon was animated and rotated. Not a big deal though if not.

**Tips on snackbar interaction from [Material guidelines]**(https://material.io/guidelines/components/snackbars-toasts.html#):
- Snackbars appear above most elements on screen, and they are equal in elevation to the floating action button. However, they are lower in elevation than dialogs, bottom sheets, and navigation drawers.
- Upon entrance, snackbars animate upwards from the bottom edge of the screen. When they appear, they do not block input.
- They exit by being swiped off-screen or automatically disappear after a timeout or user interaction elsewhere (such as summoning a new surface or activity).

**Comment by raihan-mpower** [comment]
I can work on 
"When you click on "Change status" above, it opens a modal similar to the service location dropdown"

**Comment by jasonrogena** [comment]
@cagulas The sync button reflects when the sync started

**Comment by cagulas** [comment]
@jasonrogena @rowo OK, Let's change it to when the last sync was successfully completed. Right now, it's confusing, because the sync could be failing, but according to the side menu, it appears the syncing is working, as it shows the last sync time. So, if the sync fails, it should continue to show the last successful sync time, if the sync is successful, it should update to the current time.

**Comment by cagulas** [comment]
@jasonrogena putting the last item in a new issue, since it won't be complete for this release: https://github.com/OpenSRP/opensrp-client/issues/504

**Comment by cagulas** [comment]
@jasonrogena When I turn off my wifi on my tablet, then press sync, I see the "Sync complete" snackbar message. It shouldn't show this, since there was no internet connection. I think it should show a message that sync cannot happen, because there is no internet connection. 

So maybe a snackbar message that says "Sync failed. Check your internet connection." 

Or something similar to that. What do you think?

**Comment by jasonrogena** [comment]
_"Sync failed. Check your internet connection."_ makes a lot of sense

**Comment by cagulas** [comment]
@jasonrogena I'm moving the last part about showing sync failed if offline to a new issue (https://github.com/OpenSRP/opensrp-client/issues/527), so we can close this one.

**Comment by cagulas** [comment]
Added sync failed due to error as a new issue: https://github.com/OpenSRP/opensrp-client/issues/528.

Closing this issue now.
