### ISSUE TITLE
Card sibling box: change gender avatar to sibling initials with gender colors 

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client#477]
For now, a gender icon shows up if a sibling's photo hasn't been taken. Path team has requested this be changed to the sibling's initials. This can be done after other project deliverables if there is time. 

<Img src="https://cloud.githubusercontent.com/assets/1584163/24933848/9784ebb4-1ee6-11e7-97f6-e4d00618dee7.png" width="500px">

Girl: Text: #e369e6, same size as record weight button text, Bg: #fae9fa. 

Boy: Bg: #a2eaff, Text: #43abe2

**Comment by cagulas** [comment]
Lgtm.
