### ISSUE TITLE
Implement stock control overview screen 

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#478]
The stock control module can be accessed from the side menu in the ZEIR app. 

![sc-overview](https://cloud.githubusercontent.com/assets/3488986/24949587/d2a3885a-1f76-11e7-950e-9dc70dcfa56e.png)

- [x] Tapping on the user's initials or swiping from the left opens the side menu again, where the user can return to the register view.
- [x] The six vaccines are shown as separate buttons. The number of vials shown for each vaccine is auto-calculated based on the forms the user fills out in the stock control module (received, issued, loss/adjustment).
- [x] The number of doses is auto-calculated and equals the number of vials times the number of doses in each vial (see below).
- [x] Tapping on the button takes you to the current stock view for that vaccine https://github.com/OpenSRP/opensrp-client/issues/479.

1 BCG vial = 20 doses
1 OPV vial = 20 doses
1 Penta vial = 1 dose
1 PCV vial = 2 doses
1 Rota vial = 1 dose
1 M/MR vial = 10 doses

**Comment by rowo** [comment]
@cagulas I haven't actually gone into detailed design on how to get to the stock planning and report-type stuff. I know we talked about it as an app accessible via the side menu or independently or both, and on traditional full-fledged OpenSRP it'd be on the home — but I need to think on this for a day before final requirements.

**Comment by cagulas** [comment]
@raihan-mpower Here are my suggested changes to this screen:

- [ ] Vials should be above doses
- [ ] Don't capitalize vials and doses

**Comment by cagulas** [comment]
Lgtm
