### ISSUE TITLE
Implement stock issued native form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#481]
- [x] Tapping the back button or the cancel button should open the form close confirmation message. If confirmed, the user should go back to the current stock screen for that vaccine #479 
- [x] The fields in the form should follow the fields defined in the data dictionary spreadsheet, see the "Stock Control" tab
- [x] Form styling uses same library as birth registration form
- [x] Tapping "Confirm" submits the form and updates the table in the current stock screen for that vaccine #479
- [x] Can do error states if the user tries to click "Confirm" and required fields aren't all completed. If we are using the same library as birth registration, we can treat confirm button on this form the same way.
- [x] All of the above actions should be supported both online and offline
- [x] Please note the typo in the screenshots below. It should be "vaccinated" not "vacinated"
- [x] Important note - the number they enter for stock issued should not allow the balance to become a negative number.

![227913453](https://cloud.githubusercontent.com/assets/3488986/24952582/96c33574-1f80-11e7-961d-50820f123744.png)
![228357764](https://cloud.githubusercontent.com/assets/3488986/24952590/a1a2147e-1f80-11e7-8cb2-1bf029a402dd.png)

**Comment by cagulas** [comment]
@raihan-mpower Here are my suggestions:

- [ ] Children's clinic and Other are WAY too big!
- [ ] The upper constraint is missing on the date stock issued field. It should be no greater than 1 calendar month ago.
- [ ] "Please specify" field is missing if "Other" option selected.
- [ ] Vials BCG issued is missing the asterisk. This should be a required field.
- [ ] The note underneath the vials issued field is not shown yet. The note should read "[XX] children vaccinated today. Assuming [XX] vial(s) used."
- [ ] Don't capitalize vials in "Wasted Vials"
- [ ] Remove space after colon in "New balance"
- [ ] The wasted vials are not being included in the balance calculation. See the data dictionary: New balance = {Stock_Balance} - {Vials_Issued} - {Vials_Wasted}

**Comment by raihan-mpower** [comment]
@cagulas 
"The note underneath the vials issued field is not shown yet. The note should read "[XX] children vaccinated today. Assuming [XX] vial(s) used." - this is only shown if someone is vaccinated in the date chosen....if no one is vaccinated it does not show any message......

**Comment by cagulas** [comment]
@raihan-mpower ok, but I did vaccinate someone with BCG and selected the correct date. Perhaps there's a delay before the stock module updates with vaccines given that day. Do you know if this is the case?

**Comment by raihan-mpower** [comment]
there should not be a delay , that is strange......i checked with "24-05-2017" with user biddemo

**Comment by cagulas** [comment]
Ok, let me check again.

**Comment by cagulas** [comment]
@raihan-mpower Looks really good. 

- [ ] Can you default-select Children's Clinic in the Issued form, similar to how DHO and Physical recount are default selected in the other forms?
- [ ] The note is showing for me now.  Can you add a space after the period? Can you align the message with the question label? Also, can you italicize the font, as shown in the mockups?

**Comment by cagulas** [comment]
Moved remaining issues to here: https://github.com/OpenSRP/opensrp-client-path/issues/22
