### ISSUE TITLE
Issues to resolve after April 28th release (to be complete for V1.1.3)

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-client#486]
These are listed in order of priority to work on:

**Schedules**
- [x] From issue https://github.com/OpenSRP/opensrp-client/issues/470: Recording one vaccine out of a number of vaccines that are due de-activates the overdue or due status. Eg. if four vaccines were due and one was not given, the status should remain due or overdue.
CG: I have been able to observe this with child Mary Mwelwa (ID: 1038504). I gave all 6 weeks vaccines, except for Rota 1. On the home screen, it showed due 10 weeks when it should still show due 6 weeks since Rota 1 was not given.

**Edit birth registration form**
- [x] If you take a new picture of the child, it should replace the existing one, but currently it doesn't
- [x] For required fields, if you try to save, it should automatically scroll to the part in the form that is required before submission, but currently, when you select "Save", it doesn't scroll and appears as if nothing happens.

**Location hierarchies**
- [x] Need to truncate all locations in the hierarchy that have a "so" prefix. This comes from the DHIS2 locations, where "so" means Southern Province. We don't need this, so remove "so" from the province name, district names, and health facility names (zones and residential areas do not have this, since we added these levels ourselves)

**Advanced search**
- [x] The advanced search page keeps your search parameters when you leave the advanced search page. This shouldn't happen. For instance, previously, I did a search for a child named "Julius". Later, when I scanned a QR code for another child, I selected the "search out of catchment records" option, and when it opened the page, it pre-populated the ZEIR ID from the QR code, but for some reason, it still had "Julius" showing in the first name field. It seems that the advanced search parameters are not clearing between searches.
- [x] Advanced search page UI fixes (see below)
![as](https://cloud.githubusercontent.com/assets/3488986/24860690/7d7f630e-1dfe-11e7-9868-09fdb8ac47f7.png)
- [x] UI fixes to the results page (see below)
![asr](https://cloud.githubusercontent.com/assets/3488986/24907203/e914f94c-1ec3-11e7-9b33-d002ddc2ae16.png)
- [x] In the screenshot immediately above, the results are not being filtered by active and inactive or lost to followup. In the search terms, you can see I searched for "active" kids only, yet an inactive kid was returned in the results.
- [x] Not all of the child's data is appearing after "move to my catchment" action. See screenshot below. I moved this kid from Linda to Vic Falls clinic. A lot of the data is not appearing in the detailed view, including mother guardian name, etc. 
![screenshot_20170411-125832](https://cloud.githubusercontent.com/assets/3488986/24907374/9b902c5e-1ec4-11e7-8f20-be20872597c6.png)
- [x] In the screenshot above, the locations that transferred over are appearing with their unique ID instead of the location name. Although, when I transferred another child over (Kaylaa Smithh) after this, the location name appears instead of the ID.
- [x] See screenshot below. When you move a kid to a new catchment area, the child's `Home_Facility` should change to that of the new clinic. In the screenshot below, Kaylaa was transferred from Linda to Vic Falls, but her home clinic is still appearing as Linda.
![screenshot_20170411-131728](https://cloud.githubusercontent.com/assets/3488986/24907596/83718a36-1ec5-11e7-87b0-5a5436f2abec.png)
- [x] If you move a kid to a new catchment area, they should unsync from the tablet of the previous catchment area. For example, I moved two kids from Linda to Vic Falls (Kaylaa Smithh and Smith), so they should now only appear when logged in as a user from Vic Falls. Right now, they are still appearing when I log in as a Linda user.
- [x] After you do "move to my catchment", the kid doesn't appear immediately in the home screen after the record syncs. Can this happen quicker? I had to sync and re-visit the home screen a few times for the newly synced record to appear.
- [x] The confirm form close message is different in the forms compared to the advanced search screen (the Yes, No buttons are swapped). They should be the same throughout the app, so I would replace the one on the advanced search page to match the ones in the forms.

**Detailed view**
Assigning this entire section to @raihan-mpower to start working on.
- [x] Edits for weight and vaccine data should be allowed for a period of 3 months after data is first recorded. Birth registration can always be edited and has no date limit.
- [x] The "Save" button on the top right of the detailed view screen should match the font, format, spacing, etc. of the "SAVE" form in the birth registration form.
- [x] When editing weights, the edit button only ever appears next to one weight; it should appear next to all weights (except birth weight, i.e., the weight for 0d).
- [ ] Upon selecting the edit weight option in the detailed view, the menu floats to the left before disappearing (sent email with the video, since I'm unable to attach here)
CG: Won't fix, as it's not reproducible on other tablets.
- [x] If a vaccine expires, it should show as expired on the Under Five History tab as well. For e.g., see child Beth Drew, ID: 1021005. Her OPV 0 is expired, so on the Under Five History tab, it would be nice if this showed as expired too.

**Other issues**
- [x] Mother/guardian DOB is showing as "31-12-1959" in the detailed view when the field was left blank in the form. This should remain blank in the detailed view. It should only show a DOB if the user then edits the birth registration form and adds a DOB for the mother. Currently, if you open the birth registration form to edit, it shows the default DOB in the registration form, and the user cannot even edit it.
- [ ] The mother's default DOB should be 01-01-1960, not 31-12-1959.
- [x] Inactive and Lost to Followup icons are spaced too far from their text on the home screen. See mockups.
- [x] If a child is inactive or lost to followup, the "Record weight" button should not be shown on the home screen (see mockups)
- [x] Required message alerts are not all aligned in the birth registration form (issue carried over from https://github.com/OpenSRP/opensrp-client/issues/446 issue)
- [ ] The "Record weight" button should reset 12 hours after a weight is recorded.
- [x] Add siblings in the vaccine card view for those kids that share the same mother_id i.e `select c.*  from ec_child c inner join ec_mother m on m.base_entity_id=c.relational_id where c.relational_id='{current_child_id}'`
- [x] Think there was misunderstanding in showing the green check mark on the home screen after vaccines were given. The green check should show the vaccines **that were just given**, not the ones that are due next. For instance, if birth vaccines were just given, it should show a green check and say "Birth". Right now, when you record birth vaccines, it shows a green check and 6 weeks.

**Report adverse event**
- [x] For some reason, when you open the Report Adverse Event form, it launches the date widget first. This isn't the first field in the form, so it shouldn't appear first.
- [x] The name of the form should be "Report adverse event".  Right now, it is showing as "Record an adverse event"

**Comment by cagulas** [comment]
Closing this issue. All remaining work and bugs identified during QA are moved to new issues.
