### ISSUE TITLE
Setup testing and test coverage infrastructure 

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#490]
- [ ] Fix failing tests in core i.e see why robolectric instrumentation tests are throwing exceptions
- [x] Setup jacoco as the test coverage tool
- [x] Add sample instrumentation (robolectric) and local unit tests for details page
- [x] See if it's possible to integrate jacoco coverage reports with travis

**Comment by cagulas** [comment]
This is done.
