### ISSUE TITLE
Calculate z-score

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#497]
- [x] Add a method to calculate a child's z-score, follow this equation:

![screen shot 2017-04-06 at 11 37 55 am](https://cloud.githubusercontent.com/assets/3488986/24745222/898093e2-1abd-11e7-94bc-0379a9364be6.png)

  Where:
  Z = the child's calculated z-score
  X = child's current weight in kg
  M = median weight for the child's age, obtain this value from the reference table above for the child's     given age in months
  L = the power in the Box-Cox transformation, obtain this value from the reference table above for the   child's given age in months
  S = the generalized coefficient of variation, obtain this value from the reference table above for the child's given age in months
  ** = indicates an exponent, i.e raising to the Lth power

- [x] Download and store the ref values txt file in the app assets folder in such a way that the values are read and inserted in the local db whenever the app is first installed
  For boys: http://www.who.int/childgrowth/standards/wfa_boys_0_5_zscores.txt
  For girls: http://www.who.int/childgrowth/standards/wfa_girls_0_5_zscores.txt
- [x] Add a new column z_score to the weights table
- [x] Update z-score values for existing weight records

For more background information, see [here](https://www.cdc.gov/growthcharts/percentile_data_files.htm).

**Comment by cagulas** [comment]
This is done.
