### ISSUE TITLE
adding profiling to OpenSrpSimplifyRegistry

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#5]
adding profiling to OpenSrpSimplifyRegistry or merging it with opensrprefactor and spike on modulirisation branch and fixing conflicts.

**Comment by ndisha** [comment]
@raihan-mpower is exploring other ways to handle this together with @dimasciput

**Comment by ndisha** [comment]
@raihan-mpower @dimasciput, @koros has suggested using gradle flavour for this; he shared these articles for this: http://www.techotopia.com/index.php/An_Android_Studio_Gradle_Build_Variants_Example
http://tulipemoutarde.be/2013/10/06/gradle-build-variants-for-your-android-project.html
Can you all look into this once you are done with the form technologies approaches on Wednesday?
