### ISSUE TITLE
Duplicate vaccines appearing in report adverse event form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#505]
Duplicate vaccines are appearing in the report adverse event form for some children - see Faith Achieng (ZEIR: 2562361) in biddemo tester account. Think it might have something to do if vaccines are edited to a different date?

See below:

![screenshot_2017-05-19-09-40-43](https://cloud.githubusercontent.com/assets/3488986/26236177/aca629b4-3c77-11e7-962d-98f9e10b47a7.png)

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#69
