### ISSUE TITLE
Clean up on the change status modal in ZEIR app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#506]
- [x] Add a period to the end of "Child cannot be located or contacted." 
- [x] Change "Loss" to "Lost"
- [x] Capitalize "F" and "U" in "Follow-Up"

**Comment by cagulas** [comment]
Hey @raihan-mpower do you think this will get done in time for the release next Wed?

**Comment by raihan-mpower** [comment]
@cagulas  yeah sure

**Comment by raihan-mpower** [comment]
done , this can be closed

**Comment by cagulas** [comment]
Great, can you send me a screenshot on Slack?

**Comment by raihan-mpower** [comment]
![device-2017-06-07-124029](https://user-images.githubusercontent.com/6203919/26867962-0d6d73d6-4b89-11e7-98b5-171b72804ec0.png)

**Comment by cagulas** [comment]
Lgtm.
