### ISSUE TITLE
New timeline icon for temperature/thermometer

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client#51]
@raihan-mpower It's been so long I'm not sure what the timeline icons actually look like anymore. Is there a folder if them you can send me a link to? 

Moved from https://github.com/OpenSRP/opensrp-client/issues/38:

- [ ] Temperature/thermometer on timeline
- [ ] Transition ANC visit, PNC visit icons to to using [OCHA's icons](https://thenounproject.com/ochaavmu/uploads/) in order to increase consistency. These are on the registers and the timeline

**Comment by cagulas** [comment]
@numeranazneen do you still need a thermometer / temperature icon for PNC register?

@rowo can we add the OCHA icons to the style guide with a reference on where to get them?

**Comment by rowo** [comment]
@cagulas sure I added the OCHA reference to https://github.com/OpenSRP/opensrp-client/issues/148

**Comment by cagulas** [comment]
Thanks.

@numeranazneen please comment on whether new icon is still needed.  Otherwise, will close this issue.

**Comment by numeranazneen** [comment]
Yes. We'll need that for 'PostNatal Woman Detail Page' in PNC Register

**Comment by rowo** [comment]
We are using OCHA icons as a starting point for icons going forward — if they have something relevant we'll use it. They aren't specifically health-oriented. For example in this case, they don't have a thermometer, so we'll have to make something in a similar style. The two related ones are [cold wave](https://thenounproject.com/term/cold-wave/4228/) and [heat wave](https://thenounproject.com/term/heatwave/4237/)  which is a lot like this one: https://thenounproject.com/search/?q=thermometer&i=123960. 

@numeranazneen This kind of issue could be something Sadhli can handle with the guidance that we'll be using that icon set as a stylistic guide.
