### ISSUE TITLE
Sibling box should take you to sibling vaccine card view

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#512]
Tapping on the sibling initials in a child's vaccine card should take you to the sibling's vaccine card, not their detailed view page.

**Comment by jasonrogena** [comment]
@cagulas I think this works well. Is it OK if I close the issue?

**Comment by cagulas** [comment]
@jasonrogena, no this isn't fixed yet. It currently goes to the detailed view; it should go to the vaccine card view instead.

**Comment by jasonrogena** [comment]
@cagulas Oh, OK. Sorry, I didn't read the issue well the first time

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#68
