### ISSUE TITLE
Mother/guardian NRC number not appearing

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#513]
Mother/guardian NRC number does not display in the Registration Data tab. This used to work, so I think it broke. Similarly, when you edit the birth registration form, the field is blank.

To replicate, register a new child, input the mother's NRC number. Then go to the Registration Data page. The number is missing. Then go to the edit birth registration form, the number is missing there as well.

**Comment by keymane** [comment]
@cagulas Looks like this issue was fixed, I've tested it now and am able to see the NRC number

**Comment by cagulas** [comment]
Ok cool. I tested as well. Looks ok now.
