### ISSUE TITLE
Add daily summary view in the HIA2 reporting module

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#518]
- [x] Tapping on a daily tally row in the daily tallies summary tab (https://github.com/OpenSRP/opensrp-client/issues/517) opens this view.
- [x] Tapping the back arrow or the back button on the device returns the user to the daily tallies summary tab (https://github.com/OpenSRP/opensrp-client/issues/517).
- [x] The date in the top bar is the date for the daily tally.
- [x] There are four sections shown in the daily tally summary, text below:
- Under 5 Clinic Attendance
- Growth Monitoring and Nutrition
- Immunisation
- Vitamin A, Deworming, and ITNs
- [x] Each of the above sections is expandable or collapsible by tapping on the carrot icon to the right of the section header.
- [x] The ID and Indicator columns take the labels as shown in the reporting data dictionary spreadsheet [here](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=2010018538). See the "Name" and "Label" columns in the spreadsheet.
- [x] The Value column shows the auto-calculated value for that indicator, as calculated in the app from the services recorded.
- [x] Nothing on this page should be editable. Everything is view-only.

![234670715](https://cloud.githubusercontent.com/assets/3488986/26539453/2a3380fe-4455-11e7-980d-ec49213bcc87.png)

**Comment by cagulas** [comment]
This is looking really great. Some comments below:

- [ ] Can we order the sections as per the mockups? So attendance first, then growth, immunisation, then vitamin a, etc.?
- [ ] Can we put the indicators in order within each section as per the data dictionary?
- [ ] Can we add a little more space between the ID and the Indicator columns?
- [ ] Can we add spaces to some of the indicators? I'm seeing "<12months" on a few of the child attendance indicators. We can make it "<12 months".
- [ ] Can we put "total" and "male" and "female" all in parentheses? So it should say "Attendance child health (total)" etc.
- [ ] For the IPV indicators (CHN3-027 and CHN3-027-O), the value is showing as 0, which might be confusing, since this isn't being calculated in the app. I'm thinking it might be useful to have these be static fields and the value is displayed as "NA". Especially since IPV might be added to the app at some point down the road. Is this possible?
- [ ] Related to the above, the fridge indicator is missing (CHN3-090). I'm thinking since IPV indicators are displayed, we can display the fridge indicator and have the value be static "NA". Is this possible?

**Comment by jasonrogena** [comment]
@cagulas Do they have to manually enter (even if it's 0 days) CHN3-090 at some point before they submit the report?

**Comment by cagulas** [comment]
Yea, good question, so in the daily tally summaries, which are only auto-calculated and can't be edited, we should put "N/A" for the indicators we can't calculate in the app, so IPV and fridge. For the form, however, they need to enter a number for both of these before they can submit the form. So I would leave these indicators (IPV at facility and at outreach and fridge) as blank in the form, then they'll fill in the number and submit.

**Comment by jasonrogena** [comment]
Ah, got you.

**Comment by cagulas** [comment]
@jasonrogena Changes look good. 

- [ ] Only thing to fix is two indicators for fully immunized (CHN3-080 and CHN3-080-O) were dropped.

**Comment by cagulas** [comment]
Lgtm
