### ISSUE TITLE
Design for household member detail

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client#52]
Moved from https://github.com/OpenSRP/opensrp-client/issues/38

**Comment by numeranazneen** [comment]
There will be a case in mCARE-II (and all other maternal & neonatal health care projects)  where we may need to tag two links with a woman-one for PNC Register and another for Child Register (if the woman delivered a baby). Currently in HH Inhabitants page, we put a single link for each woman which is showing her current Register link. So, in this scenario where there will be two links for each woman, we will need to redesign the HH Inhabitants page to place multiple links for single woman.

**Comment by numeranazneen** [comment]
If we can tag the child with the mother in this way, then the Search option in HH Register will serve the purpose of Global Search for now. Because, using the Search option currently we are able to search any woman  who is registered in the system and also getting the link to her current Register.

**Comment by rowo** [comment]
![screenshot_2015-06-30-14-01-38](https://cloud.githubusercontent.com/assets/1584163/8456430/567d8c1a-1fd9-11e5-9695-2cf332dd441e.png)

**Comment by rowo** [comment]
@numeranazneen do you still need a mockup of this screen? I can just make up placeholder information here for the children + additional wife? That ok?

**Comment by numeranazneen** [comment]
Hi @rowo I will need Kelsey's feedback before sending you any confirmation. She was too busy this week so we couldn't manage to have the meeting to discuss this. So far my suggestion is to put Child ID, Gender and Age for Child Row that will be tagged to the New Mother.

**Comment by rowo** [comment]
Here is the screen with minimal changes. Even more minimally, you can use full rows and not containers for additional women-children groups, but hopefully soon once the functionality gets in there we can get the visual design corrected overall.

![hh-inhabitants](https://cloud.githubusercontent.com/assets/1584163/8550906/73f793a4-24a1-11e5-8746-e59a259b1a4b.png)

Icon:
![icon-indent](https://cloud.githubusercontent.com/assets/1584163/8550917/90f92260-24a1-11e5-8d2b-0d29c8723f28.png)

**Comment by numeranazneen** [comment]
Thank you so much Roger. Can we show the age in days first, then in months, then eventually go up to years? Because knowing the day and month will help the Health Assistants to vaccinate the child.

**Comment by cagulas** [comment]
We just discussed this on our call.  I will share the cutoffs that were used in Dristhi, and BD team will adapt the cutoffs as needed for their health workers.  @numeranazneen for the next version of mockups that you do, it would be good to show an example of each, so one child with age in days, one with age in months, and one with age in years.

**Comment by cagulas** [comment]
Am closing this now.  @numeranazneen will incorporate these designs in next version of mockups
