### ISSUE TITLE
Update side menu to incorporate new modules

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#523]
The side menu in the ZEIR app should be updated to allow the user to navigate to the new modules in the app, i.e, stock and HIA2 reports.

- [x] Change the text of the "Register" option to "Add new child". This is to make it clear that this opens the birth registration form and does not take you to the register view.
- [x] The current module that the user is on should be highlighted. I.e if they are looking at the main register view, then the ZEIR option should be highlighted in blue when they open the side menu (see Screen 1). Same goes for the stock and HIA2 modules.
- [x] Selecting the ZEIR module takes the user to the main register view.
- [x] Selecting the HIA2 Report module takes the user to the HIA2 daily tally summary view (https://github.com/OpenSRP/opensrp-client/issues/517).
- [x] Selecting the Stock module takes the user to the Stock module overview screen (https://github.com/OpenSRP/opensrp-client/issues/478).

Screen 1: ZEIR app register view is currently selected
![233397825](https://cloud.githubusercontent.com/assets/3488986/26541930/84cad7f0-4460-11e7-825e-695f7e9f3eea.png)

Screen 2: HIA2 report module is currently selected
![234563483](https://cloud.githubusercontent.com/assets/3488986/26541946/960a915e-4460-11e7-9a06-baaecf9d5aaa.png)

Screen 3: Stock module is currently selected
![234563493](https://cloud.githubusercontent.com/assets/3488986/26541956/a9a5f58c-4460-11e7-9693-e5e89b3bb0a5.png)

**Comment by raihan-mpower** [comment]
@rowo @cagulas can i get the icons for these new items. i.e stock control and hia 2 reports . Zeir icon i am guessing is the app logo?

**Comment by rowo** [comment]
@raihan-mpower here are some invisible icons
![icon-menu-outofarea](https://user-images.githubusercontent.com/1584163/26878937-36921766-4b5d-11e7-80bd-92ccd1de8435.png)
![icon-menu-sync](https://user-images.githubusercontent.com/1584163/26878939-3693cc50-4b5d-11e7-9f35-78ac89158ddd.png)
![icon-menu-add](https://user-images.githubusercontent.com/1584163/26878936-3691b366-4b5d-11e7-9ed7-3900b36f721f.png)
![icon-menu-hia2](https://user-images.githubusercontent.com/1584163/26878938-369286c4-4b5d-11e7-803e-90b055784596.png)
![icon-menu-stock](https://user-images.githubusercontent.com/1584163/26878935-368e77f0-4b5d-11e7-9b44-ec4a11778fb9.png)
![icon-menu-zeir](https://user-images.githubusercontent.com/1584163/26878934-368e72be-4b5d-11e7-9180-e8dd23db6253.png)

**Comment by cagulas** [comment]
@raihan-mpower Here is some feedback from Roger and myself:

![menu-feedback](https://user-images.githubusercontent.com/3488986/27385422-4cba7576-569b-11e7-87fb-391508dd4057.png)

- [ ] Don't capitalize "C" in "Add new Child"
- [ ] Don't capitalize "Out of Catchment Vaccination" - it should say "Record out of catchment vaccination"
- [ ] Stock Control icon is not aligned with HIA2 and ZEIR icons

**Comment by cagulas** [comment]
Lgtm
