### ISSUE TITLE
Check for child duplicates in birth registration form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#526]
In the birth registration form, use the lookup widget to check for possible child duplicates that might already exist on the app.

Similar to the mother lookup, display a notification if there are possible child duplicate matches based on the following fields:

Mother_Guardian_First_Name
Last_Name
Date_Birth
Sex

These are additive, meaning only display the duplicate alert if all four fields are a match.

The lookup widget should then display the possible child duplicate matches, similar to how the mother matches are displayed (showing the child's first name, last name, mother/guardian first name, mother/guardian last name, date of birth, and sex) then give the user two options:

1. Cancel the lookup and continue filling in the form (i.e. none of the possible matches are the same child); or 
2. Allow the user to select a match, which could take them to the child's vaccine card or detailed view, where they can further verify the match. 

@rowo I don't remember any mockup on this, but what are your thoughts on the above proposed interaction?

**Comment by rowo** [comment]
@cagulas Yes, seems okay. I don't remember the order of the questions so I don't remember if they are grouped nicely, but it checks after the last field same as mother lookup. And I'm guessing this only searches on-device.

**Comment by cagulas** [comment]
This feature is partially redundant. Duplicate records will be prevented by using QR code stickers.
