### ISSUE TITLE
Some birth registration form edits do not reflect in detailed view UI until later

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#529]
After editing the birth registration form and adding a mother DOB (it was left blank in the original form submission), the new DOB does not appear till after you visit the home register screen and revisit the child detail page. Some other edits appear immediately, so can we make all edits update immediately in the app?

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#67
