### ISSUE TITLE
ZEIR version 1.1.3 Feedback 

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#532]
- [ ] vaccinations: When a user registers a child who is 6 weeks and above,
both OPV 0 and OPV1 are coming up as due. OPV0 should be inactive after 13 days.

CG: This is the intended behavior, and confirmed this with @paulnindi. The individual vaccines, however, should have date constraints on them. I.e. OPV 0 should only be given between DOB and 13 days of age. These date constraints have been added in issue https://github.com/OpenSRP/opensrp-client/issues/500

- [ ] Vaccinations: ''Record all'' functionality doesn't seem to appear on all the grouped vaccines. e.g record a child who is older than 10 weeks, after recording the 6 weeks vaccines, the 10 weeks vaccines become active but the option for recording all vaccines doesn't pop up. Sometimes it appears and sometimes it doesnt. 

CG: New issue created for this here: https://github.com/OpenSRP/opensrp-client/issues/533

- [ ] Vaccinations: App is able to accept the same date for vaccines that cannot be administered on same date. e.g. if a 1 year old baby is registered, user is able to input the same date for OPV0, BCG, Rota 1, Rota2, DPT1, DPT2, DPT3.PCV1,PCV2,PCV3, Measles etc. Not all vaccines can be given  on the same date, therefore control on vaccines that cannot be administered on the same date should be added. For example DPT2 cannot be given earlier or same date as DPT1. 

CG: This was fixed with this issue: https://github.com/OpenSRP/opensrp-client/issues/500.

- [ ] Registration: Concern coming up is on editing. Some fields such as Sex, Date first seen, Child's DOB, Birth weight, Place of birth, have been defined not to be editable fields as to data dictionary.  Field observations suggest some nurses sometimes do make mistakes on some fields and usually would require editing. I would like to suggest  having these fields editable at-least within the day and can be locked out. 

CG: This is something to discuss further. There isn't existing functionality to be able to allow edits to the birth registration form for a period of time before locking the variables. Currently, how this is handled is that an admin would need to make any necessary changes in the OpenMRS instance, and these changes would sync back to the app.

- [ ] weight:  Weight Taken earlier accepts dates earlier that the Date of Birth. A constraint can be added like that of the the vaccine button which will not allow dates earlier than date of birth. 

CG: To be covered in existing issue: https://github.com/OpenSRP/opensrp-client/issues/509

**Comment by cagulas** [comment]
Closing this. Each point is addressed in a new or existing issue.
