### ISSUE TITLE
"Record all" button disappears occasionally

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#533]
As noted in https://github.com/OpenSRP/opensrp-client/issues/532, the "Record all" button disappears occasionally from children's vaccine cards in the app. Look into why this is happening and ensure the "Record all" option is always displayed.

**Comment by keymane** [comment]
@cagulas this should be fixed. The button appears whenever there is a vaccine enabled in the group

**Comment by cagulas** [comment]
Ok, excellent, we'll package this issue with the next release.

**Comment by cagulas** [comment]
Lgtm!
