### ISSUE TITLE
Calculate HIA2 indicators for fully immunised (< 1 year) at facility and outreach

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#537]
- [x] CHN3-80- Number of children < one year who have received the complete BCG, OPV series, DPT-Hib+Hep1 series, PCV series , RV series and measles/MR 1 within 10 days of each antigen being due at this facility 
- [x] CHN3-80-O- Number of children < one year who have received the complete BCG, OPV series, DPT-Hib+Hep1 series, PCV series , RV series and measles/MR 1 within 10 days of each antigen being due at outreach conducted by this facility

**Comment by cagulas** [comment]
Lgtm. I see both indicators in the daily tally and monthly report views.
