### ISSUE TITLE
BID FEEDBACK  - ZEIR May/June Releases

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#538]
- [ ] Immunization: The BCG Reminder is popping up on some children but the option to record the BCG 2nd dose doesn't appear. Additionally there should also be a way of terminating the alert i.e if the scar is available. Noticed also that  BCG 2nd Dose is not listed in the Vaccine History of a child.

CG: This is covered in https://github.com/OpenSRP/opensrp-client/issues/426, which is still a WIP.

- [ ] Immunization: When user changes the status to inactive or lost for follow up, it requires the user to remember to change the status back to active when they show-up. It will be good to have systems revert to active automatically when a vaccine or service is given. 

CG: This should be addressed in this issue https://github.com/OpenSRP/opensrp-client/issues/515

- [ ] Weight Edit: should allow the user to type decimal. Decimal is pre entered. Need to make it uniform with normal entering of weight were user types the decimal.

CG: Am creating a new issue to address this: https://github.com/OpenSRP/opensrp-client/issues/539

- [ ] Recording a  child who is 6 months activates Vitamin A IFC2 which is a dose for period 0 - 5 months. The system should activate Vitamin A 1 since its 6 months (However posses a challenge on back entry i.e it will mean that Vitamin A IFC2 cannot be back entered if it was given earlier. (This might need  discussion.) 

CG: Am including this point in the current discussion issue here: https://github.com/OpenSRP/opensrp-client/issues/534

**Comment by cagulas** [comment]
Each point is addressed in other issues, am closing this.
