### ISSUE TITLE
Fix decimal and child icon color on edit weight modal

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#539]
In the edit weight modal, the decimal is automated, which does not match the original data entry for weight interaction. The decimal should not be automated. The user needs to type in the decimal, as in the current weight data entry modal.

Also, the avatar shown in the edit weight modal for girls is blue, when it should be pink.

**Comment by keymane** [comment]
Fixed https://github.com/OpenSRP/opensrp-client/pull/552

**Comment by cagulas** [comment]
Lgtm
