### ISSUE TITLE
Feedback - Zeir 1.1.5 

### ISSUE THREAD

**Issue by paulnindi** [OpenSRP/opensrp-client#542]
- [ ] Location Hierarchy: the zones for Nyawa facility in Kazungula district are not coming out in a particular order but rather in a random fashion e.g - Zone 1, Zone 10, Zone 7 etc
CG: This can't be fixed right now. This is how locations are ordered in DHIS2 and in OMRS, so we cannot alter this. If there are more than 10 locations, it will be ordered 1, 10, 2, 3, etc.
- [x] Death of a child: Apparently child doesn't get archived when child is marked as deceased. user is able to fill in the deceased form but upon saving, nothing happens. There is no indication that the child has been marked deceased. The record remains active on the home screen.
CG: Fixed in this issue: https://github.com/OpenSRP/opensrp-server/issues/299
- [x] Duplicates: One facility recorded the child twice because they couldn't edit the child's DOB. The facility name is Nakatindi. Assist with checking and merging of the records.
CG: We are compiling these administrative changes separately, outside of github
- [x] Synchronization: sync status can be  misleading. I have observed that sometimes the app gives a ''sync complete'' notification even when the app hasn't finished syncing all records with the server. I think if the internet is bad or cuts during the sync process, the notification says ''sync complete''. This is the case even in offline mode, if you tap on the sync button, the notification says sync complete. I think we don't have a sure way of telling that a records has been uploaded or all records have been downloaded. (For downloading records, is it possible to implement a notification mechanism which shows total number being downloaded e.g 'downloading 1 out of 100'.). 
Worst case scenario  am thinking in line with this, is a facility losing a tablet or a fresh installation has to be done for some reason.
CG: New issue created for this: https://github.com/OpenSRP/opensrp-server/issues/298

**Comment by cagulas** [comment]
All comments addressed.
