### ISSUE TITLE
Implement UI update for Vitamin A data modal

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#545]
In the Vitamin A data modal, let's add a comma in the number of IU, e.g `50,000` instead of `50000` and `100,000` instead of `100000`. Also, the units should be `IU` and not `UI` for all Vitamin A doses.

**Comment by keymane** [comment]
Fixed https://github.com/OpenSRP/opensrp-client/pull/551

**Comment by cagulas** [comment]
Lgtm
