### ISSUE TITLE
Put ZEIR on Google Play Store

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#548]

**Comment by jasonrogena** [comment]
We'll need the following:

 - [ ] A short description of the ZEIR app (up to 80 characters) @cagulas 
 - [ ] Full description of the ZEIR app (up to 4000 characters) @cagulas
 - [ ] Hi-res ZEIR icon (512x512 pixels) @rowo 
 - [ ] Feature graphic for the app. More info on the feature graphic [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en)  (1024x500 pixels) @rowo

**Comment by cagulas** [comment]
@jasonrogena How about the following:

**Short description (up to 80 characters)**
A mobile health app that allows users to register children and track their vaccinations

**Longer description (up to 4,000 characters)**
The Zambia Electronic Immunization Registry (ZEIR) was created for Zambia’s Ministry of Health to give to nurses working in public health facilities to track the healthcare services provided to children under the age of five living in the facility’s catchment area. The nurse can log in to the application on her Android tablet to register children at birth and record all of their healthcare services till the age of five, including: vaccinations, weight, vitamin A, deworming, and bednet distribution. The app combines current mHealth best practices – automated scheduling and reminders, decision support, offline support, and automated reporting – to help nurses provide timely and quality care to the children in their communities. The app integrates with Zambia’s national health information system (HIS) to help automate the reporting process from healthcare facilities in Zambia to the district level.

ZEIR is powered by OpenSRP (smartregister.org), an open source Android application and platform geared towards frontline health workers in developing countries.

**Comment by rowo** [comment]
![zeir_icon-rounded](https://user-images.githubusercontent.com/1584163/28049384-273ef2ca-65c5-11e7-9b51-42391f7009fa.png)

**Comment by jasonrogena** [comment]
@cagulas which privacy policy should we use?

**Comment by keymane** [comment]
Update client app to use https rather than http server url

**Comment by rowo** [comment]
@jasonrogena @cagulas 
![zeir-plastore-feature](https://user-images.githubusercontent.com/1584163/29951606-d2aae430-8e91-11e7-8e22-ef12250da8a8.png)

**Comment by cagulas** [comment]
Looks awesome, thanks @rowo

**Comment by cagulas** [comment]
PATH team confirmed we can use the https://github.com/onaio/steps-app/wiki/Privacy-Policy privacy policy (please make sure to replace all mention of STEPS app with ZEIR), since they haven't gotten feedback on other language yet.

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#32
