### ISSUE TITLE
The expansion icon button in growth chart is not active yet

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#556]
Moving from https://github.com/OpenSRP/opensrp-client/issues/469

I added an expansion icon button to the previous weights section of the growth chart. I think this can behave where either (A) the top portion (above the done button) gets longer or (B) the entire card contents get longer.

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#31
