### ISSUE TITLE
Opensrp Android Nougat: Detected problems with app native libraries

### ISSUE THREAD

**Issue by mib-iqbal** [OpenSRP/opensrp-client#563]
we just upgrade our Samsung Galaxy tab s 2 to Android 7.0  and now get the following popup while working with our app, we tried to use m-care too and the same issue happens:
![screenshot_20170718-060948](https://user-images.githubusercontent.com/9330687/28300785-62cc2890-6bb4-11e7-8e95-6559a5ee80ca.png)

@keymane 
Could you please check this out

**Comment by jasonrogena** [comment]
This is how we solved it for the PATH app -> https://github.com/OpenSRP/opensrp-client/commit/480efbf5463c927b7f4afc933933de398d039126

**Comment by mib-iqbal** [comment]
Thanks
