### ISSUE TITLE
ZEIR v1.2.2. Record weight is a mondatory field regardless of the place of birth being home.

### ISSUE THREAD

**Issue by tobiasmakai** [OpenSRP/opensrp-client#564]
If a child was born at home no weight is recorded at birth. When the child is being registered to ZEIR, the weight provided at registration date is recorded as the birth weight - 0d weight.

**Comment by cagulas** [comment]
I think if a child is weighed within the first week, it can be classified as birth weight still. Are you proposing that if place of birth, home, is selected, birth weight should not be a mandatory field?

**Comment by tobiasmakai** [comment]
The confusion comes in when the recorded weight at 6days old shows as weight at 0day old. The issue is it is not representing the actual weight at birth since when the child is born at home they don't record weight in most circumstances. I think it should not be a mandatory field.

**Comment by cagulas** [comment]
We discussed this on the BID weekly call, and there are no changes we will make.
