### ISSUE TITLE
Due dates for vaccines are not displaying 

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client#565]
Due vaccine column shows previous vaccines that have already been given to the patient. 

![screenshot_2017-09-05-16-02-47 1](https://user-images.githubusercontent.com/17847885/30062471-f6136300-9253-11e7-97e4-83c7febb450f.png)

**Comment by jasonrogena** [comment]
This issue was moved to OpenSRP/opensrp-client-path#28
