### ISSUE TITLE
converting to gradle build system

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#59]
It is important for us to convert the current structure from maven to gradle , as this is used and recomended by android studio .
I believe this would also help in modularisation and adding new libraries.

**Comment by pld** [comment]
:+1: I'm a big fan of gradle

**Comment by cagulas** [comment]
@dimasciput what is the status on this?

**Comment by dimasciput** [comment]
@cagulas Hi Carolyn, I just commit it : https://github.com/OpenSRP/opensrp-client/pull/68
Waiting @raihan-mpower to review it.

**Comment by cagulas** [comment]
Excellent.  Thank you @dimasciput.

**Comment by ndisha** [comment]
This was done and merged!
