### ISSUE TITLE
merging spike on modularisation with master

### ISSUE THREAD

**Issue by raihan-mpower** [OpenSRP/opensrp-client#6]
Review and adding the spike on modularisation branch with master

**Comment by ndisha** [comment]
@raihan-mpower @dimasciput this is still pending... Lets review the pull request and either discard it or merge it.

**Comment by raihan-mpower** [comment]
we cannot merge this as this ends up as broken code.............
@dimasciput and I agreed to discard this.
This separated core code from the packages in to a module resulting in the ide giving errors.
This also makes building a hassle.
We can go the modularisation route once we are done fixing the core components.
