### ISSUE TITLE
Icons/logos requested for ID OpenSRP prototype 2

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#60]
- [ ] Happy Bidan Figure for Front of App 

Icon for Detailed View Timelines: 
- [x] Pregnant Lady 
- [x] Baby
- [x] Tablets/Pills
- [x] Needle (Immunisation)

Risk Flags Icons: 
- [x] Yellow RT Flag (same as HR)
- [x] Red RTK Flag (same as HRP)
- [x] Orange RTP Flag (same as BPL)
- [x] Purple RTA

**Comment by rowo** [comment]
Put into Thrive Cons.. / Thrive Indo.. / Phase 2.. / img

Breaking out the bidan figure into a new issue.
