### ISSUE TITLE
faulty logic on the opensrp ELCO forms

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#70]
@raihan-mpower, it seems the new .apk has faulty form logic around the questions asked to the MWRA since all my women have the tag: NOT In ELCO, see the screenshot below:

![screenshot_2015-07-27-05-43-30](https://cloud.githubusercontent.com/assets/801106/8903257/4c8731da-345f-11e5-865f-430ae70bd08c.png)

This has happened with the latest .apk, never observed it before. Also, none of the submission get couchDB and by extension OpenMRS, please look into this?

@julkarnain @sohelsarder @dimasciput @numeranazneen

**Comment by numeranazneen** [comment]
Hi @ndisha I just submit a form with a ELCO woman in the Household and it is showing perfectly in the HH Inhabitants page (check the screenshot). The latest forms that have been added in the APK has also been uploaded in beta.ona.io. You can check the updated logic from there and submit another form.

As far I know @julkarnain has also worked on the same version of the updated form. 

![screenshot_2015-07-27-16-22-41](https://cloud.githubusercontent.com/assets/12798060/8904623/df940a7a-3482-11e5-8e66-71514b4e6a9c.png)

**Comment by ndisha** [comment]
Thanks @numeranazneen. Please confirm, are you able to view the data submitted on OpenMRS?

Also, please share a link to the latest .apk on mail or on hipchat - seems you have the working version..

**Comment by ndisha** [comment]
This was fixed, closing the issue!
