### ISSUE TITLE
Replacing enketo on OpenSRP

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#73]
OpenSRP enketo forms currently are pretty slow and we should explore replacing these as soon as possible. The options we are looking at include:

ODK - what would we need to change to make ODK work for us in OpenSRP?
(Para Pesquisa - Brazilian form builder and Android survey app): https://github.com/LaFabbrica/para-pesquisa-android

Android json form: https://github.com/vijayrawatsan/android-json-form-wizard
@mberg @cagulas @koros @raihan-mpower @dimasciput @sohelsarder @julkarnain @euclidian

**Comment by ndisha** [comment]
Related to https://github.com/OpenSRP/opensrp-client/issues/7.

**Comment by ndisha** [comment]
@dimasciput @raihan-mpower has detailed the approaches here: https://docs.google.com/document/d/16klMkALrHP6qc8e6tUbzYCf_6kgKQo-SXljqiGw383o/edit#

**Comment by koros** [comment]
This issue has been resolved by employing the faster form loading technique
