### ISSUE TITLE
About date widget in xforms

### ISSUE THREAD

**Issue by naveen-kommuri** [OpenSRP/opensrp-client#88]
Want to know about the changes for date widget working properly, because date widget not appears properly.

**Comment by ndisha** [comment]
@naveen-kommuri what do you mean 'date widget not appearing properly'? What is the exact problem you are encountering?

**Comment by naveen-kommuri** [comment]
In Xforms date widget working is differed based on the devices, in few devices when I open the date widget(DOB field)  in the form and tap on the outside of the screen the date widget is being closed and  not displayed again. I have to re-open the form again and again in order to overcome this issue. Let me know if still any clarification needed on the above

**Comment by ndisha** [comment]
Hey @naveen-kommuri, this has been fixed with latest release. Please get the most updated code (from master branch) and let us know if the problem still persists.

**Comment by naveen-kommuri** [comment]
Can you point me only the date widget related changes.

**Comment by koros** [comment]
This issue is now fixed please see https://github.com/OpenSRP/opensrp-client/issues/127
