### ISSUE TITLE
what should I expect to see after taking the NID/BRID picture

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#90]
@raihan-mpower, what was the action expected after taking the above photo? For the HH head photo, after taking it, I can view it in place of the HH image, what was the plan for the NID card? I could not see any change.

**Comment by numeranazneen** [comment]
In the updated APK, we have also integrated the ID image option in HH Inhabitants page. Please check the updated APK  from the link below-
https://drive.google.com/file/d/0B9AKt4Ln_f4HOXNEZU45OXhvU2M/view?usp=sharing

**Comment by cagulas** [comment]
I see it.  Looks good, but the only thing is that there is no way to tell whether image is already taken or not, since the taken image is not displayed anywhere.  Are there plans to display the image that is taken?

**Comment by cagulas** [comment]
Also, is the exclamation point in the below image added on purpose to indicate that the NID/BRID id card pic needs to be taken?  If so, why is it necessary to add this icon to the top blue bar as well?

![screenshot_2015-09-29-12-42-46](https://cloud.githubusercontent.com/assets/3488986/10171446/29184a10-66a8-11e5-8f5c-07cb73746428.png)

**Comment by numeranazneen** [comment]
Ans1:  If image will be taken, exclamatory sign will be gone for that particular entry which will ensure that image has been taken. This image will be used for data analysis purpose, so there is a plan to develop a front end portal later, where they can see these images to crosscheck with the FWAs  collected/typed the ID.

Ans2: If you'll select the top exclamatory sign it'll filter the list with all exclamatory signed rows. It'll help the FWA to find out which houses have missing IDs.

**Comment by ndisha** [comment]
@numeranazneen on Ans 2, I am not sure I understand how this would happen because, BRID and NID are both person_identifiers and as such are mandatory so essentially you cant have missing values. For my case, I picked BRID and entered the value:
<img width="904" alt="screen shot 2015-10-01 at 5 25 43 pm" src="https://cloud.githubusercontent.com/assets/801106/10241889/727e53f8-68f5-11e5-9544-592a5c7c5bdf.png">

But after submitting, I get:
![screenshot_2015-10-01-10-01-23](https://cloud.githubusercontent.com/assets/801106/10241900/8325603e-68f5-11e5-9c1f-49603e8eb7b8.png)
![screenshot_2015-10-01-10-04-43](https://cloud.githubusercontent.com/assets/801106/10241930/b0237706-68f5-11e5-98ed-18bf8b73f839.png)

Could this be a bug? @raihan-mpower @koros

**Comment by ndisha** [comment]
@raihan-mpower @numeranazneen I am still getting empty NID/BRID even with the latest .APK; check out Stephanie and Gina on these screenshots.

![screenshot_2015-10-07-09-08-43](https://cloud.githubusercontent.com/assets/801106/10338502/16362c92-6d0f-11e5-9b78-5abce898af24.png)
![screenshot_2015-10-07-09-08-49](https://cloud.githubusercontent.com/assets/801106/10338503/1638083c-6d0f-11e5-8069-947d9d5d7780.png)

**Comment by numeranazneen** [comment]
If that's the case, this is definitely a Bug. And we fixed that in 5th Oct release. Unfortunately we are not getting this error anymore. Will check again and let you know. Thanks.
