### ISSUE TITLE
PSRF form not accessible even when due date is past

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#91]
@raihan-mpower @numeranazneen @cagulas at what point and in which register should we view the PSRF form? I thought it should be under the ELCO register (which I figured has the schedules configured since I see the PSRF Due date column there). The 2 women created using the user: Sohel, had a PSRF Due Date of 23rd September 2015, see below:

![screenshot_2015-09-25-10-48-34](https://cloud.githubusercontent.com/assets/801106/10104003/09b5e5d8-63b0-11e5-9a7e-c817a372169f.png)

However, I cant open their PSRF forms. Thought I should raise this for checking.

**Comment by numeranazneen** [comment]
If you submit a FWNewHH/Census form it'll schedule the PSRF immediately in ELCO, you can click on the form then. You didn't mention how you have generated the PSRF forms-is it from FWNewHH? Census? or PSRF?

**Comment by ndisha** [comment]
Thanks @numeranazneen, I was not able submit a new form to see this, but I found a workaround for the  GPS widget (I type in the coordinates) and on submitting, I saw the PSRF form. Thanks!
