### ISSUE TITLE
Updates to HH register walkthrough 

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#95]
Below is some UI clean up for the HH register walkthrough:

1. Update text in below screenshot to read "**Tap to open New Household Registration form**".  Or "**Tap to register a new household**" is also fine I think.

![screen shot 2015-10-07 at 2 10 22 pm](https://cloud.githubusercontent.com/assets/3488986/10346690/661262e6-6cfe-11e5-9d16-bce4f67ecacb.png)

This is the name of the form, so good to say actual form name.  Instead of 'click' which implies clicking with a mouse, the better verb to use here is 'tap'

2. Update text in below screenshot to read "**Tap on the search panel and type to search by head of household name, inhabitant name, Jivita HHID, or GOB HHID.**"

![screen shot 2015-10-07 at 2 10 34 pm](https://cloud.githubusercontent.com/assets/3488986/10346821/13840ccc-6cff-11e5-9771-34361a013c4f.png)

3. Update text in below screenshot to read "**Tap here to open the filter menu**".  I would also move the bottom arrow to the right.  The bottom arrow is directly under 'clicking here' which implies the user should click below instead of tapping the filter button above.  Also, please capitalize 'ok' button, should be 'OK'.

![screen shot 2015-10-07 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/3488986/10346973/c2176022-6cff-11e5-943e-41ff5d43bdcc.png)

**Comment by cagulas** [comment]
Also, you can see the background in all 3 screens are different shades of grey.  Please make these consistent.  I would choose a darker grey, so that you don't have to update the HH register screenshot every time there's a change in the UI.

**Comment by numeranazneen** [comment]
Thanks for rephrasing the instructions. Raihan will fix this.

We also found the inconsistency in the background colors at the very beginning, but at that time this was a low priority task and required potential time of Raihan, so we didn't fix this at that moment. But later we got use to it ! Thanks for notifying this.

**Comment by cagulas** [comment]
You're welcome.  Agree it's lower priority, so this issue can sit for whenever Raihan has the chance to get to it.

**Comment by cagulas** [comment]
Cool, I see most of these changes have been implemented.  What is remaining, I think is:

- Add a space between name, and Jivita
![screen shot 2015-10-25 at 4 06 47 pm](https://cloud.githubusercontent.com/assets/3488986/10714644/9edd4d46-7b33-11e5-9086-487d8eb7f48d.png)

- Update screenshot since modal now says ELCO instead of MWRA.
![screen shot 2015-10-25 at 4 06 57 pm](https://cloud.githubusercontent.com/assets/3488986/10714649/b896944a-7b33-11e5-8da4-03135801f446.png)

- I would also move the 'ok' button more to the left and capitalize ok to OK

- I still think the arrows should be reversed or switched up.  Currently, the arrow under 'tap here' makes it seem like you need to tap on the menu instead of the actual filter button.

**Comment by cagulas** [comment]
Will replace with a more up to date issue, since this has been sitting a while.
