### ISSUE TITLE
Instead of MWRA, should this say ELCO?

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#96]
@numeranazneen Since we use the term ELCO in the app, should the filter menu buttons say ELCO instead of MWRA?  Let's be consistent.
![screen shot 2015-10-07 at 2 12 07 pm](https://cloud.githubusercontent.com/assets/3488986/10347130/8781c8ac-6d00-11e5-8b19-09b141c89b39.png)

**Comment by numeranazneen** [comment]
Yes. Sounds logical !

**Comment by cagulas** [comment]
Ok, great.  Reassigning to @raihan-mpower then.

**Comment by raihan-mpower** [comment]
but all mwra are not necessarily elco...............so should i change this to no of elco? @numeranazneen

**Comment by numeranazneen** [comment]
you are right @raihan-mpower .....sorry I forgot.  

@cagulas I just checked the form, we used a calculation field at the bottom of the form, named 'MWRA' where we are calculating all the woman in the HH (who has a first name), this includes both eligible and non-eligible woman. Raihan actually used this field in the app to show the 'Number of MWRA'. So, as he said, it's not necessarily mean that all MWRA are ELCO. Better to keep it as is, no? or you think it should be called something general like 'Woman'?

**Comment by cagulas** [comment]
Ok, thanks for this.  The original intention of displaying No. of MWRA is for the FWA to know which households she needs to target for visits if there are eligible women in them.  According to Kelsey, non-ELCO women are not considered clients in the mCare app, so let's confirm the intended behavior with Kelsey.  Since non-ELCO women don't need to be visited, maybe having no. of ELCO women shown is more useful for the FWA.  Let's confirm with Kelsey.

**Comment by klzeller** [comment]
The way we think about MWRAs at JiVitA is as Married Women of Reproductive Age (who are not menopausal / sterilized / etc).  So for us, an MWRA is the same thing as an ELCO woman.  At this point to make things easier, if the calculation and coding is for all women regardless of eligibility, we could update the column heading to No. of Registered Women so that we don't need to make coding level changes.  We should change one of these though, either the calculation or the heading, so the meaning matches the calculation.  Which is easier from the coding side?

**Comment by numeranazneen** [comment]
As per the existing logic, I think 'No of MWRA' depends on the question 'Is there any woman age 15-49....?' (this means MWRA).  If the answer is 'No', then it'll show 0, if the answer is 'Yes' then it'll ask generic questions about the women in the HH and show the count of both Eligible & Non Eligible woman. So, here's a difference between MWRA count and ELCO count.

**Comment by cagulas** [comment]
No. of MWRA in the register view is taken from MWRA variable in the HHReg and Census forms.  This variable counts all women registered in the repeat group, both eligible and non-eligible.  

We should do what makes the most sense for the FWA workers and their expected workflow.  Let's discuss on our call in 15 min.

**Comment by cagulas** [comment]
On the call, it was decided to change MWRA to ELCO in the app view.  Will close this issue and create a new issue for this task.  I've updated the calculation in the form to count only ELCO instead of all women.
