### ISSUE TITLE
No MWRA and One or more MWRA should be separate from village filter

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#97]
See below.  Currently, the **No MWRA** and the **Has one or more MWRA** are in the same filter menu as the mauza-paras.  

![screen shot 2015-10-07 at 2 12 07 pm](https://cloud.githubusercontent.com/assets/3488986/10348159/7d496200-6d05-11e5-9e03-13cf5250ebf1.png)

The intention is that these filters can be used on top of one another.  For instance, the FWA should be able to filter to a mauza-para, and then add the MWRA filter on top of that.  I think keeping these two filters in same menu is not so useful for the FWA.

In Dristhi, we handled this by having a second dropdown (where the service mode dropdown traditionally went), see below:

![screen_shot_2015-10-07_at_3_08_43_pm](https://cloud.githubusercontent.com/assets/3488986/10348264/10e9d288-6d06-11e5-9aa7-b0b02c5b7c84.png)

This was in the Family Planning register in Dristhi.  ANM could filter by village in separate village filter, then she could filter by priority status in this dropdown.  Selecting **2+ children** filters the list to only those clients who have 2 or more children, and then village filter can be selected on top of this.

@numeranazneen how does this look?

**Comment by numeranazneen** [comment]
Looks good. But in ELCO register we only have Filter by Mauza option. So, if we'll remove the Mauza from this filter option and put that in a separate filter option in HH Register, then we should maintain the same in ELCO register for consistency. But we don't have anything else to filter in ELCO Register. What'll be your suggestion about this?

Just wanted to add, the current filtering option had been developed based on the below document-
https://docs.google.com/document/d/1XLTYeLhnGKNQCo0bKP6qfb_ys4cP9r2bXQGLaCVFvKE/edit

So, we should also ask Kelsey's suggestion to this.

**Comment by numeranazneen** [comment]
Can you please add Kelsey here as well?

**Comment by cagulas** [comment]
I think that's fine.  In ELCO register, no. of MWRA is not displayed in register view, so no need to have this filter in ELCO register.  Mauza filter is fine in ELCO register as is, I think.  You would leave Mauza filter where it is (same filter button), and you would move the MWRA filters out of that filter, not vice versa.  See the Dristhi screenshot above.  MWRA filter would move to the center button.  Let me know if that makes sense.

Let me email Kelsey to have her get on GitHub.

**Comment by numeranazneen** [comment]
Yes, that makes sense. I'll ask @raihan-mpower  to update the APK with this revised requirement, once we'll get KZ's feedback on this.

**Comment by cagulas** [comment]
Sounds good.

**Comment by raihan-mpower** [comment]
@numeranazneen is this issue addressed in current app? does this require any pending task?
