### ISSUE TITLE
Enketo form freezes on submit and have to exit form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#98]
See below.  This is in the Oct 6 release.  I hit the submit button on the Enketo form, and the form freezes, and I'm unable to press the submit button again.  I had to exit out of the form by hitting the back button and tapping yes on the prompt that all data will be lost.  Even though I did this, somehow the form was submitted and the new HH appears in the register.  

![screen shot 2015-10-07 at 4 05 00 pm](https://cloud.githubusercontent.com/assets/3488986/10349655/95387ce0-6d0d-11e5-8b51-4213c356c25c.png)

**Comment by numeranazneen** [comment]
Have you got this several times? I mean can you let us know how to regenerate this bug?

Yesterday, when I was testing, I found similar kind of issue, when I tap the date field (at the top of the form) couple of times, it showed a blue border around the input box, but didn't show the calendar, I was able to input the rest of the questions but was not able to input that date. So I had to exit from the form and re-enter data again.

**Comment by cagulas** [comment]
Yea, maybe related.  I got this a few times yesterday.  Each time it was with the NewHH Reg form.  Upon form submit button, the form would freeze.  Will comment if it happens more today.  Could be related to the Genymotion.
