### ISSUE TITLE
Female HH head icon needed if HH head is female

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#99]
In the New HH Registration form, the gender of HH head is asked.  Regardless of whether male or female is selected, the resulting HH head person icon shown in register is male.  If female is selected, a female icon should display instead.

**Comment by raihan-mpower** [comment]
done...will be seen in next release

**Comment by cagulas** [comment]
Great, thanks. Should I close this issue now?

**Comment by raihan-mpower** [comment]
yea you can or you can wait for the next apk and test it and then close this issue

**Comment by cagulas** [comment]
cool, I'll wait for next apk

**Comment by cagulas** [comment]
Checked this and it looks good.  This was added in Oct 21, 2015 release.

**Comment by cagulas** [comment]
Sorry, re-opening this, because female icon needed on inhabitants page as well.  Currently, female icon shows up in register view, but if you tap into the inhabitants page, the male icon is shown still.

**Comment by raihan-mpower** [comment]
fixed it in latest release
